/* CUSTOMER USERS */
export const GET_CHANNELLIST = "GET_CHANNELLIST";
export const GET_CHANNELLIST_SUCCESS = "GET_CHANNELLIST_SUCCESS";
export const GET_CHANNELLIST_FAIL = "GET_CHANNELLIST_FAIL";
export const GET_CAS_SOURCE = "GET_CAS_SOURCE";
export const GET_CAS_SOURCE_SUCCESS = "GET_CAS_SOURCE_SUCCESS";
export const GET_CAS_SOURCE_FAIL = "GET_CAS_SOURCE_FAIL";

export const ADD_NEW_CHANNELLIST = "ADD_NEW_CHANNELLIST";
export const ADD_CHANNELLIST_SUCCESS = "ADD_CHANNELLIST_SUCCESS";
export const ADD_CHANNELLIST_FAIL = "ADD_CHANNELLIST_FAIL";

export const UPDATE_CHANNELLIST_CURRENT_PAGE =
  "UPDATE_CHANNELLIST_CURRENT_PAGE";
