/* CUSTOMER USERS */
export const GET_CHANNELLIST = "GET_CHANNELLIST";
export const GET_CHANNELLIST_SUCCESS = "GET_CHANNELLIST_SUCCESS";
export const GET_CHANNELLIST_FAIL = "GET_CHANNELLIST_FAIL";

export const GET_CHANNELLIST_DEFINITION = "GET_CHANNELLIST_DEFINITION";
export const GET_CHANNELLIST_DEFINITION_SUCCESS = "GET_CHANNELLIST_DEFINITION_SUCCESS";
export const GET_CHANNELLIST_DEFINITION_FAIL = "GET_CHANNELLIST_DEFINITION_FAIL";

export const GET_CHANNELLIST_TYPE = "GET_CHANNELLIST_TYPE";
export const GET_CHANNELLIST_TYPE_SUCCESS = "GET_CHANNELLIST_TYPE_SUCCESS";
export const GET_CHANNELLIST_TYPE_FAIL = "GET_CHANNELLIST_TYPE_FAIL";

export const GET_CHANNELLIST_STATUS = "GET_CHANNELLIST_STATUS";
export const GET_CHANNELLIST_STATUS_SUCCESS = "GET_CHANNELLIST_STATUS_SUCCESS";
export const GET_CHANNELLIST_STATUS_FAIL = "GET_CHANNELLIST_STATUS_FAIL";

export const GET_CHANNELLIST_CASCODE = "GET_CHANNELLIST_CASCODE";
export const GET_CHANNELLIST_CASCODE_SUCCESS = "GET_CHANNELLIST_CASCODE_SUCCESS";
export const GET_CHANNELLIST_CASCODE_FAIL = "GET_CHANNELLIST_CASCODE_FAIL";

export const GET_CHANNELLIST_GENRE = "GET_CHANNELLIST_GENRE";
export const GET_CHANNELLIST_GENRE_SUCCESS = "GET_CHANNELLIST_GENRE_SUCCESS";
export const GET_CHANNELLIST_GENRE_FAIL = "GET_CHANNELLIST_GENRE_FAIL";

export const GET_CHANNELLIST_BROADCASTER = "GET_CHANNELLIST_BROADCASTER";
export const GET_CHANNELLIST_BROADCASTER_SUCCESS = "GET_CHANNELLIST_BROADCASTER_SUCCESS";
export const GET_CHANNELLIST_BROADCASTER_FAIL = "GET_CHANNELLIST_BROADCASTER_FAIL";

export const GET_CHANNELLIST_LANGUAGE = "GET_CHANNELLIST_LANGUAGE";
export const GET_CHANNELLIST_LANGUAGE_SUCCESS = "GET_CHANNELLIST_LANGUAGE_SUCCESS";
export const GET_CHANNELLIST_LANGUAGE_FAIL = "GET_CHANNELLIST_LANGUAGE_FAIL";

export const GET_CAS_SOURCE = "GET_CAS_SOURCE";
export const GET_CAS_SOURCE_SUCCESS = "GET_CAS_SOURCE_SUCCESS";
export const GET_CAS_SOURCE_FAIL = "GET_CAS_SOURCE_FAIL";

export const ADD_NEW_CHANNELLIST = "ADD_NEW_CHANNELLIST";
export const ADD_CHANNELLIST_SUCCESS = "ADD_CHANNELLIST_SUCCESS";
export const ADD_CHANNELLIST_FAIL = "ADD_CHANNELLIST_FAIL";

export const UPDATE_CHANNELLIST = "UPDATE_CHANNELLIST";
export const UPDATE_CHANNELLIST_SUCCESS = "UPDATE_CHANNELLIST_SUCCESS";
export const UPDATE_CHANNELLIST_FAIL = "UPDATE_CHANNELLIST_FAIL";

export const UPDATE_CHANNELLIST_CURRENT_PAGE =
  "UPDATE_CHANNELLIST_CURRENT_PAGE";
