/* CUSTOMER USERS */
export const GET_CHANNELLIST = "GET_CHANNELLIST";
export const GET_CHANNELLIST_SUCCESS = "GET_CHANNELLIST_SUCCESS";
export const GET_CHANNELLIST_FAIL = "GET_CHANNELLIST_FAIL";

export const ADD_NEW_CHANNELLIST =
    "ADD_NEW_CHANNELLIST";
export const ADD_CHANNELLIST_SUCCESS =
    "ADD_CHANNELLIST_SUCCESS";
export const ADD_CHANNELLIST_FAIL =
    "ADD_CHANNELLIST_FAIL";
