export const GET_COMPLAINTCATEGORY = "GET_COMPLAINTCATEGORY";
export const GET_COMPLAINTCATEGORY_SUCCESS = "GET_COMPLAINTCATEGORY_SUCCESS";
export const GET_COMPLAINTCATEGORY_FAIL = "GET_COMPLAINTCATEGORY_FAIL";

export const GET_COMPLAINTCATEGORY_STATUS = "GET_COMPLAINTCATEGORY_STATUS";
export const GET_COMPLAINTCATEGORY_STATUS_SUCCESS = "GET_COMPLAINTCATEGORY_STATUS_SUCCESS";
export const GET_COMPLAINTCATEGORY_STATUS_FAIL = "GET_COMPLAINTCATEGORY_STATUS_FAIL";

export const ADD_NEW_COMPLAINTCATEGORY =
    "ADD_NEW_COMPLAINTCATEGORY";
export const ADD_COMPLAINTCATEGORY_SUCCESS =
    "ADD_COMPLAINTCATEGORY_SUCCESS";
export const ADD_COMPLAINTCATEGORY_FAIL =
    "ADD_COMPLAINTCATEGORY_FAIL";