export const GET_COMPLAINTCATEGORY = "GET_COMPLAINTCATEGORY";
export const GET_COMPLAINTCATEGORY_SUCCESS = "GET_COMPLAINTCATEGORY_SUCCESS";
export const GET_COMPLAINTCATEGORY_FAIL = "GET_COMPLAINTCATEGORY_FAIL";
