/* CUSTOMER USERS */
export const GET_PACKAGELIST = "GET_PACKAGELIST";
export const GET_PACKAGELIST_SUCCESS = "GET_PACKAGELIST_SUCCESS";
export const GET_PACKAGELIST_FAIL = "GET_PACKAGELIST_FAIL";

export const ADD_NEW_PACKAGELIST =
    "ADD_NEW_PACKAGELIST";
export const ADD_PACKAGELIST_SUCCESS =
    "ADD_PACKAGELIST_SUCCESS";
export const ADD_PACKAGELIST_FAIL =
    "ADD_PACKAGELIST_FAIL";