/* CUSTOMER USERS */
export const GET_PACKAGELIST = "GET_PACKAGELIST";
export const GET_PACKAGELIST_SUCCESS = "GET_PACKAGELIST_SUCCESS";
export const GET_PACKAGELIST_FAIL = "GET_PACKAGELIST_FAIL";

export const GET_PACKAGE_TYPE = "GET_PACKAGE_TYPE";
export const GET_PACKAGE_TYPE_SUCCESS = "GET_PACKAGE_TYPE_SUCCESS";
export const GET_PACKAGE_TYPE_FAIL = "GET_PACKAGE_TYPE_FAIL";

export const GET_PACKAGE_BOXTYPE = "GET_PACKAGE_BOXTYPE";
export const GET_PACKAGE_BOXTYPE_SUCCESS = "GET_PACKAGE_BOXTYPE_SUCCESS";
export const GET_PACKAGE_BOXTYPE_FAIL = "GET_PACKAGE_BOXTYPE_FAIL";

export const GET_PACKAGE_STATUS = "GET_PACKAGE_STATUS";
export const GET_PACKAGE_STATUS_SUCCESS = "GET_PACKAGE_STATUS_SUCCESS";
export const GET_PACKAGE_STATUS_FAIL = "GET_PACKAGE_STATUS_FAIL";

export const ADD_NEW_PACKAGELIST = "ADD_NEW_PACKAGELIST";
export const ADD_PACKAGELIST_SUCCESS = "ADD_PACKAGELIST_SUCCESS";
export const ADD_PACKAGELIST_FAIL = "ADD_PACKAGELIST_FAIL";

export const UPDATE_PACKAGELIST_CURRENT_PAGE =
  "UPDATE_PACKAGELIST_CURRENT_PAGE";
