export const GET_LOCATION = "GET_LOCATION";
export const GET_LOCATION_SUCCESS = "GET_LOCATION_SUCCESS";
export const GET_LOCATION_FAIL = "GET_LOCATION_FAIL";

export const ADD_LOCATION = "ADD_LOCATION";
export const ADD_LOCATION_SUCCESS = "ADD_LOCATION_SUCCESS";
export const ADD_LOCATION_FAIL = "ADD_LOCATION_FAIL";

export const UPDATE_LOCATION = "UPDATE_LOCATION";
export const UPDATE_LOCATION_SUCCESS = "UPDATE_LOCATION_SUCCESS";
export const UPDATE_LOCATION_FAIL = "UPDATE_LOCATION_FAIL";

export const GET_LCO_ONLOCATION = "GET_LCO_ONLOCATION";
export const GET_LCO_ONLOCATION_SUCCESS = "GET_LCO_ONLOCATION_SUCCESS";
export const GET_LCO_ONLOCATION_FAIL = "GET_LCO_ONLOCATION_FAIL";

export const GET_SINGLE_LOCATION = "GET_SINGLE_LOCATION";
export const GET_SINGLE_LOCATION_SUCCESS = "GET_SINGLE_LOCATION_SUCCESS";
export const GET_SINGLE_LOCATION_FAIL = "GET_SINGLE_LOCATION_FAIL";

export const UPDATE_LOCATION_CURRENT_PAGE = "UPDATE_LOCATION_CURRENT_PAGE";