export const GET_INVENTORYTRACK = "GET_INVENTORYTRACK";
export const GET_INVENTORYTRACK_SUCCESS = "GET_INVENTORYTRACK_SUCCESS";
export const GET_INVENTORYTRACK_FAIL = "GET_INVENTORYTRACK_FAIL";

export const UPDATE_INVENTORYTRACK_CURRENT_PAGE =
  "UPDATE_INVENTORYTRACK_CURRENT_PAGE";
