export const GET_INVENTORYTRACK = "GET_INVENTORYTRACK";
export const GET_INVENTORYTRACK_SUCCESS = "GET_INVENTORYTRACK_SUCCESS";
export const GET_INVENTORYTRACK_FAIL = "GET_INVENTORYTRACK_FAIL";

export const UPDATE_INVENTORYTRACK_CURRENT_PAGE =
  "UPDATE_INVENTORYTRACK_CURRENT_PAGE";

export const GET_INVENTORYTRACK_ACTION = "GET_INVENTORYTRACK_ACTION";
export const GET_INVENTORYTRACK_ACTION_SUCCESS =
  "GET_INVENTORYTRACK_ACTION_SUCCESS";
export const GET_INVENTORYTRACK_ACTION_FAIL = "GET_INVENTORYTRACK_ACTION_FAIL";
