/* USERS */
export const GET_USERS = "GET_USERS";
export const GET_USERS_SUCCESS = "GET_USERS_SUCCESS";
export const GET_USERS_FAIL = "GET_USERS_FAIL";

export const GET_USER_TYPE = "GET_USER_TYPE";
export const GET_USER_TYPE_SUCCESS = "GET_USER_TYPE_SUCCESS";
export const GET_USER_TYPE_FAIL = "GET_USER_TYPE_FAIL";

export const GET_USER_STATUS = "GET_USER_STATUS";
export const GET_USER_STATUS_SUCCESS = "GET_USER_STATUS_SUCCESS";
export const GET_USER_STATUS_FAIL = "GET_USER_STATUS_FAIL";

export const GET_USER_ROLE = "GET_USER_ROLE";
export const GET_USER_ROLE_SUCCESS = "GET_USER_ROLE_SUCCESS";
export const GET_USER_ROLE_FAIL = "GET_USER_ROLE_FAIL";

export const GET_USER_DESIGNATION = "GET_USER_DESIGNATION";
export const GET_USER_DESIGNATION_SUCCESS = "GET_USER_DESIGNATION_SUCCESS";
export const GET_USER_DESIGNATION_FAIL = "GET_USER_DESIGNATION_FAIL";

export const GET_USER_MSO_POLICY = "GET_USER_MSO_POLICY";
export const GET_USER_MSO_POLICY_SUCCESS = "GET_USER_MSO_POLICY_SUCCESS";
export const GET_USER_MSO_POLICY_FAIL = "GET_USER_MSO_POLICY_FAIL";

export const GET_USER_MSO_DETAILS = "GET_USER_MSO_DETAILS";
export const GET_USER_MSO_DETAILS_SUCCESS = "GET_USER_MSO_DETAILS_SUCCESS";
export const GET_USER_MSO_DETAILS_FAIL = "GET_USER_MSO_DETAILS_FAIL";

export const GET_USER_REGIONALOFFICE = "GET_USER_REGIONALOFFICE";
export const GET_USER_REGIONALOFFICE_SUCCESS =
  "GET_USER_REGIONALOFFICE_SUCCESS";
export const GET_USER_REGIONALOFFICE_FAIL = "GET_USER_REGIONALOFFICE_FAIL";

export const GET_USER_DISTRIBUTOR = "GET_USER_DISTRIBUTOR";
export const GET_USER_DISTRIBUTOR_SUCCESS = "GET_USER_DISTRIBUTOR_SUCCESS";
export const GET_USER_DISTRIBUTOR_FAIL = "GET_USER_DISTRIBUTOR_FAIL";

export const GET_USER_LCO = "GET_USER_LCO";
export const GET_USER_LCO_SUCCESS = "GET_USER_LCO_SUCCESS";
export const GET_USER_LCO_FAIL = "GET_USER_LCO_FAIL";

/* USERS PROFILE */
export const GET_USER_PROFILE = "GET_USER_PROFILE";
export const GET_USER_PROFILE_SUCCESS = "GET_USER_PROFILE_SUCCESS";
export const GET_USER_PROFILE_FAIL = "GET_USER_PROFILE_FAIL";

/**
 * add user
 */
export const ADD_NEW_USER = "ADD_NEW_USER";
export const ADD_USER_SUCCESS = "ADD_USER_SUCCESS";
export const ADD_USER_FAIL = "ADD_USER_FAIL";

/**
 * Edit user
 */
export const UPDATE_USER = "UPDATE_USER";
export const UPDATE_USER_SUCCESS = "UPDATE_USER_SUCCESS";
export const UPDATE_USER_FAIL = "UPDATE_USER_FAIL";

/**
 * Delete user
 */
export const DELETE_USER = "DELETE_USER";
export const DELETE_USER_SUCCESS = "DELETE_USER_SUCCESS";
export const DELETE_USER_FAIL = "DELETE_USER_FAIL";
