export const GET_APPADBANNER = "GET_APPADBANNER";
export const GET_APPADBANNER_SUCCESS = "GET_APPADBANNER_SUCCESS";
export const GET_APPADBANNER_FAIL = "GET_APPADBANNER_FAIL";

export const ADD_APPADBANNER = "ADD_APPADBANNER";
export const ADD_APPADBANNER_SUCCESS = "ADD_APPADBANNER_SUCCESS";
export const ADD_APPADBANNER_FAIL = "ADD_APPADBANNER_FAIL";
