export const GET_INVENTORYBLACKLISTED_SMARTCARD =
  "GET_INVENTORYBLACKLISTED_SMARTCARD";
export const GET_INVENTORYBLACKLISTED_SMARTCARD_SUCCESS =
  "GET_INVENTORYBLACKLISTED_SMARTCARD_SUCCESS";
export const GET_INVENTORYBLACKLISTED_SMARTCARD_FAIL =
  "GET_INVENTORYBLACKLISTED_SMARTCARD_FAIL";

export const GET_INVENTORYBLACKLISTED_STB = "GET_INVENTORYBLACKLISTED_STB";
export const GET_INVENTORYBLACKLISTED_STB_SUCCESS =
  "GET_INVENTORYBLACKLISTED_STB_SUCCESS";
export const GET_INVENTORYBLACKLISTED_STB_FAIL =
  "GET_INVENTORYBLACKLISTED_STB_FAIL";

export const GET_INVENTORYBLACKLISTED_PAIRING =
  "GET_INVENTORYBLACKLISTED_PAIRING";
export const GET_INVENTORYBLACKLISTED_PAIRING_SUCCESS =
  "GET_INVENTORYBLACKLISTED_PAIRING_SUCCESS";
export const GET_INVENTORYBLACKLISTED_PAIRING_FAIL =
  "GET_INVENTORYBLACKLISTED_PAIRING_FAIL";

export const UPDATE_BLACKLISTEDPAIRING_CURRENT_PAGE =
  "UPDATE_BLACKLISTEDPAIRING_CURRENT_PAGE";
