/* CUSTOMER USERS */
export const GET_SCHEDULECUSTOMERNOTIFICATION = "GET_SCHEDULECUSTOMERNOTIFICATION"
export const GET_SCHEDULECUSTOMERNOTIFICATION_SUCCESS = "GET_SCHEDULECUSTOMERNOTIFICATION_SUCCESS"
export const GET_SCHEDULECUSTOMERNOTIFICATION_FAIL = "GET_SCHEDULECUSTOMERNOTIFICATION_FAIL"

export const ADD_SCHEDULECUSTOMERNOTIFICATION = "ADD_NEW_SCHEDULECUSTOMERNOTIFICATION";
export const ADD_SCHEDULECUSTOMERNOTIFICATION_SUCCESS = "ADD_SCHEDULECUSTOMERNOTIFICATION_SUCCESS";
export const ADD_SCHEDULECUSTOMERNOTIFICATION_FAIL = "ADD_SCHEDULECUSTOMERNOTIFICATION_FAIL";