/* CUSTOMER USERS */
export const GET_SCHEDULECUSTOMERNOTIFICATION =
  "GET_SCHEDULECUSTOMERNOTIFICATION";
export const GET_SCHEDULECUSTOMERNOTIFICATION_SUCCESS =
  "GET_SCHEDULECUSTOMERNOTIFICATION_SUCCESS";
export const GET_SCHEDULECUSTOMERNOTIFICATION_FAIL =
  "GET_SCHEDULECUSTOMERNOTIFICATION_FAIL";

export const GET_SCHEDULECUSTOMERNOTIFICATION_TYPE = "GET_SCHEDULECUSTOMERNOTIFICATION_TYPE";
export const GET_SCHEDULECUSTOMERNOTIFICATION_TYPE_SUCCESS = "GET_SCHEDULECUSTOMERNOTIFICATION_TYPE_SUCCESS";
export const GET_SCHEDULECUSTOMERNOTIFICATION_TYPE_FAIL = "GET_SCHEDULECUSTOMERNOTIFICATION_TYPE_FAIL";

export const GET_SCHEDULECUSTOMERNOTIFICATION_STATUS = "GET_SCHEDULECUSTOMERNOTIFICATION_STATUS";
export const GET_SCHEDULECUSTOMERNOTIFICATION_STATUS_SUCCESS = "GET_SCHEDULECUSTOMERNOTIFICATION_STATUS_SUCCESS";
export const GET_SCHEDULECUSTOMERNOTIFICATION_STATUS_FAIL = "GET_SCHEDULECUSTOMERNOTIFICATION_STATUS_FAIL";

export const GET_SCHEDULECUSTOMERNOTIFICATION_OSD = "GET_SCHEDULECUSTOMERNOTIFICATION_OSD";
export const GET_SCHEDULECUSTOMERNOTIFICATION_OSD_SUCCESS = "GET_SCHEDULECUSTOMERNOTIFICATION_OSD_SUCCESS";
export const GET_SCHEDULECUSTOMERNOTIFICATION_OSD_FAIL = "GET_SCHEDULECUSTOMERNOTIFICATION_OSD_FAIL";

export const GET_SCHEDULECUSTOMERNOTIFICATION_BMAIL = "GET_SCHEDULECUSTOMERNOTIFICATION_BMAIL";
export const GET_SCHEDULECUSTOMERNOTIFICATION_BMAIL_SUCCESS = "GET_SCHEDULECUSTOMERNOTIFICATION_BMAIL_SUCCESS";
export const GET_SCHEDULECUSTOMERNOTIFICATION_BMAIL_FAIL = "GET_SCHEDULECUSTOMERNOTIFICATION_BMAIL_FAIL";

export const GET_SCHEDULECUSTOMERNOTIFICATION_SMS = "GET_SCHEDULECUSTOMERNOTIFICATION_SMS";
export const GET_SCHEDULECUSTOMERNOTIFICATION_SMS_SUCCESS = "GET_SCHEDULECUSTOMERNOTIFICATION_SMS_SUCCESS";
export const GET_SCHEDULECUSTOMERNOTIFICATION_SMS_FAIL = "GET_SCHEDULECUSTOMERNOTIFICATION_SMS_FAIL";



export const ADD_NEW_SCHEDULECUSTOMERNOTIFICATION =
  "ADD_NEW_SCHEDULECUSTOMERNOTIFICATION";
export const ADD_SCHEDULECUSTOMERNOTIFICATION_SUCCESS =
  "ADD_SCHEDULECUSTOMERNOTIFICATION_SUCCESS";
export const ADD_SCHEDULECUSTOMERNOTIFICATION_FAIL =
  "ADD_SCHEDULECUSTOMERNOTIFICATION_FAIL";
