/* CUSTOMER USERS */
export const GET_SCHEDULECUSTOMERNOTIFICATION = "GET_SCHEDULECUSTOMERNOTIFICATION"
export const GET_SCHEDULECUSTOMERNOTIFICATION_SUCCESS = "GET_SCHEDULECUSTOMERNOTIFICATION_SUCCESS"
export const GET_SCHEDULECUSTOMERNOTIFICATION_FAIL = "GET_SCHEDULECUSTOMERNOTIFICATION_FAIL"

