/* CUSTOMER USERS */
export const GET_LOCALCHANNELNUMBER = "GET_LOCALCHANNELNUMBER"
export const GET_LOCALCHANNELNUMBER_SUCCESS = "GET_LOCALCHANNELNUMBER_SUCCESS"
export const GET_LOCALCHANNELNUMBER_FAIL = "GET_LOCALCHANNELNUMBER_FAIL"

