/* CUSTOMER USERS */
export const GET_COMPANYLIST = "GET_COMPANYLIST";
export const GET_COMPANYLIST_SUCCESS = "GET_COMPANYLIST_SUCCESS";
export const GET_COMPANYLIST_FAIL = "GET_COMPANYLIST_FAIL";

export const ADD_NEW_COMPANYLIST =
    "ADD_NEW_COMPANYLIST";
export const ADD_COMPANYLIST_SUCCESS =
    "ADD_COMPANYLIST_SUCCESS";
export const ADD_COMPANYLIST_FAIL =
    "ADD_COMPANYLIST_FAIL";
