export const GET_REASON = "GET_REASON";
export const GET_REASON_SUCCESS = "GET_REASON_SUCCESS";
export const GET_REASON_FAIL = "GET_REASON_FAIL";

export const UPDATE_REASON = "UPDATE_REASON";
export const UPDATE_REASON_SUCCESS = "UPDATE_REASON_SUCCESS";
export const UPDATE_REASON_FAIL = "UPDATE_REASON_FAIL";

export const GET_REASON_STATUS = "GET_REASON_STATUS";
export const GET_REASON_STATUS_SUCCESS = "GET_REASON_STATUS_SUCCESS";
export const GET_REASON_STATUS_FAIL = "GET_REASON_STATUS_FAIL";

export const GET_REASON_REASONTYPE = "GET_REASON_REASONTYPE";
export const GET_REASON_REASONTYPE_SUCCESS = "GET_REASON_REASONTYPE_SUCCESS";
export const GET_REASON_REASONTYPE_FAIL = "GET_REASON_REASONTYPE_STATUS_FAIL";

export const ADD_REASON =
    "ADD_REASON";
export const ADD_REASON_SUCCESS =
    "ADD_REASON_SUCCESS";
export const ADD_REASON_FAIL =
    "ADD_REASON_FAIL";

export const UPDATE_REASON_CURRENT_PAGE = "UPDATE_REASON_CURRENT_PAGE";