export const GET_BRANDLIST = "GET_BRANDLIST";
export const GET_BRANDLIST_SUCCESS = "GET_BRANDLIST_SUCCESS";
export const GET_BRANDLIST_FAIL = "GET_BRANDLIST_FAIL";

export const ADD_BRANDLIST = "ADD_BRANDLIST";
export const ADD_BRANDLIST_SUCCESS = "ADD_BRANDLIST_SUCCESS";
export const ADD_BRANDLIST_FAIL = "ADD_BRANDLIST_FAIL";
