export const GET_BRANDLIST = "GET_BRANDLIST";
export const GET_BRANDLIST_SUCCESS = "GET_BRANDLIST_SUCCESS";
export const GET_BRANDLIST_FAIL = "GET_BRANDLIST_FAIL";

export const GET_BRANDLIST_BRANDTYPE = "GET_BRANDLIST_BRANDTYPE";
export const GET_BRANDLIST_BRANDTYPE_SUCCESS = "GET_BRANDLIST_BRANDTYPE_SUCCESS";
export const GET_BRANDLIST_BRANDTYPE_FAIL = "GET_BRANDLIST_BRANDTYPE_FAIL";

export const GET_BRANDLIST_BOXTYPE = "GET_BRANDLIST_BOXTYPE";
export const GET_BRANDLIST_BOXTYPE_SUCCESS = "GET_BRANDLIST_BOXTYPE_SUCCESS";
export const GET_BRANDLIST_BOXTYPE_FAIL = "GET_BRANDLIST_BOXTYPE_FAIL";

export const GET_BRANDLIST_CHARACTERS = "GET_BRANDLIST_CHARACTERS";
export const GET_BRANDLIST_CHARACTERS_SUCCESS = "GET_BRANDLIST_CHARACTERS_SUCCESS";
export const GET_BRANDLIST_CHARACTERS_FAIL = "GET_BRANDLIST_CHARACTERS_FAIL";

export const GET_BRANDLIST_STATUS = "GET_BRANDLIST_STATUS";
export const GET_BRANDLIST_STATUS_SUCCESS = "GET_BRANDLIST_STATUS_SUCCESS";
export const GET_BRANDLIST_STATUS_FAIL = "GET_BRANDLIST_STATUS_FAIL";

export const GET_BRANDLIST_CASTYPE = "GET_BRANDLIST_CASTYPE";
export const GET_BRANDLIST_CASTYPE_SUCCESS = "GET_BRANDLIST_CASTYPE_SUCCESS";
export const GET_BRANDLIST_CASTYPE_FAIL = "GET_BRANDLIST_CASTYPE_FAIL";

export const ADD_BRANDLIST = "ADD_BRANDLIST";
export const ADD_BRANDLIST_SUCCESS = "ADD_BRANDLIST_SUCCESS";
export const ADD_BRANDLIST_FAIL = "ADD_BRANDLIST_FAIL";
