export const GET_NCF = "GET_NCF";
export const GET_NCF_SUCCESS = "GET_NCF_SUCCESS";
export const GET_NCF_FAIL = "GET_NCF_FAIL";

export const ADD_NCF = "ADD_NCF";
export const ADD_NCF_SUCCESS = "ADD_NCF_SUCCESS";
export const ADD_NCF_FAIL = "ADD_NCF_FAIL";

export const GET_OPERATOR_FORBULKASSIGN = "GET_OPERATOR_FORBULKASSIGN";
export const GET_OPERATOR_FORBULKASSIGN_SUCCESS =
  "GET_OPERATOR_FORBULKASSIGN_SUCCESS";
export const GET_OPERATOR_FORBULKASSIGN_FAIL =
  "GET_OPERATOR_FORBULKASSIGN_FAIL";

export const ADD_BULKASSIGN_NCF = "ADD_BULKASSIGN_NCF";
export const ADD_BULKASSIGN_NCF_SUCCESS = "ADD_BULKASSIGN_NCF_SUCCESS";
export const ADD_BULKASSIGN_NCF_FAIL = "ADD_BULKASSIGN_NCF_FAIL";

export const UPDATE_NCF = "UPDATE_NCF";
export const UPDATE_NCF_SUCCESS = "UPDATE_NCF_SUCCESS";
export const UPDATE_NCF_FAIL = "UPDATE_NCF_FAIL";
