/* CUSTOMER USERS */
export const GET_SMSMESSAGETEMPLIST = "GET_SMSMESSAGETEMPLIST";
export const GET_SMSMESSAGETEMPLIST_SUCCESS = "GET_SMSMESSAGETEMPLIST_SUCCESS";
export const GET_SMSMESSAGETEMPLIST_FAIL = "GET_SMSMESSAGETEMPLIST_FAIL";

export const UPDATE_SMSMESSAGETEMPLIST = "UPDATE_SMSMESSAGETEMPLIST";
export const UPDATE_SMSMESSAGETEMPLIST_SUCCESS = "UPDATE_SMSMESSAGETEMPLIST_SUCCESS";
export const UPDATE_SMSMESSAGETEMPLIST_FAIL = "UPDATE_SMSMESSAGETEMPLIST_FAIL";

export const GET_SMSMESSAGETEMPLIST_STATUS = "GET_SMSMESSAGETEMPLIST_STATUS";
export const GET_SMSMESSAGETEMPLIST_STATUS_SUCCESS = "GET_SMSMESSAGETEMPLIST_STATUS_SUCCESS";
export const GET_SMSMESSAGETEMPLIST_STATUS_FAIL = "GET_SMSMESSAGETEMPLIST_STATUS_FAIL";

export const GET_SMSMESSAGETEMPLIST_SUBCATEGORY = "GET_SMSMESSAGETEMPLIST_SUBCATEGORY";
export const GET_SMSMESSAGETEMPLIST_SUBCATEGORY_SUCCESS = "GET_SMSMESSAGETEMPLIST_SUBCATEGORY_SUCCESS";
export const GET_SMSMESSAGETEMPLIST_SUBCATEGORY_FAIL = "GET_SMSMESSAGETEMPLIST_SUBCATEGORY_FAIL";

export const GET_SMSMESSAGETEMPLIST_CATEGORY = "GET_SMSMESSAGETEMPLIST_CATEGORY";
export const GET_SMSMESSAGETEMPLIST_CATEGORY_SUCCESS = "GET_SMSMESSAGETEMPLIST_CATEGORY_SUCCESS";
export const GET_SMSMESSAGETEMPLIST_CATEGORY_FAIL = "GET_SMSMESSAGETEMPLIST_CATEGORY_FAIL";

export const GET_SMSMESSAGETEMPLIST_SENDER = "GET_SMSMESSAGETEMPLIST_SENDER";
export const GET_SMSMESSAGETEMPLIST_SENDER_SUCCESS = "GET_SMSMESSAGETEMPLIST_SENDER_SUCCESS";
export const GET_SMSMESSAGETEMPLIST_SENDER_FAIL = "GET_SMSMESSAGETEMPLIST_SENDER_FAIL";


export const ADD_NEW_SMSMESSAGETEMPLIST =
    "ADD_NEW_SMSMESSAGETEMPLIST";
export const ADD_SMSMESSAGETEMPLIST_SUCCESS =
    "ADD_SMSMESSAGETEMPLIST_SUCCESS";
export const ADD_SMSMESSAGETEMPLIST_FAIL =
    "ADD_SMSMESSAGETEMPLIST_FAIL";

export const UPDATE_SMSMESSAGETEMPLIST_CURRENT_PAGE = "UPDATE_SMSMESSAGETEMPLIST_CURRENT_PAGE";