/* CUSTOMER USERS */
export const GET_SMSMESSAGETEMPLIST = "GET_SMSMESSAGETEMPLIST";
export const GET_SMSMESSAGETEMPLIST_SUCCESS = "GET_SMSMESSAGETEMPLIST_SUCCESS";
export const GET_SMSMESSAGETEMPLIST_FAIL = "GET_SMSMESSAGETEMPLIST_FAIL";
