/* CUSTOMER USERS */
export const GET_SMSMESSAGETEMPLIST = "GET_SMSMESSAGETEMPLIST";
export const GET_SMSMESSAGETEMPLIST_SUCCESS = "GET_SMSMESSAGETEMPLIST_SUCCESS";
export const GET_SMSMESSAGETEMPLIST_FAIL = "GET_SMSMESSAGETEMPLIST_FAIL";

export const ADD_NEW_SMSMESSAGETEMPLIST =
    "ADD_NEW_SMSMESSAGETEMPLIST";
export const ADD_SMSMESSAGETEMPLIST_SUCCESS =
    "ADD_SMSMESSAGETEMPLIST_SUCCESS";
export const ADD_SMSMESSAGETEMPLIST_FAIL =
    "ADD_SMSMESSAGETEMPLIST_FAIL";