export const GET_BOUQUET = "GET_BOUQUET";
export const GET_BOUQUET_SUCCESS = "GET_BOUQUET_SUCCESS";
export const GET_BOUQUET_FAIL = "GET_BOUQUET_FAIL";

export const ADD_BOUQUET = "ADD_BOUQUET";
export const ADD_BOUQUET_SUCCESS = "ADD_BOUQUET_SUCCESS";
export const ADD_BOUQUET_FAIL = "ADD_BOUQUET_FAIL";

export const GET_BOUQUETTYPE = "GET_BOUQUETTYPE";
export const GET_BOUQUETTYPE_SUCCESS = "GET_BOUQUETTYPE_SUCCESS";
export const GET_BOUQUETTYPE_FAIL = "GET_BOUQUETTYPE_FAIL";

export const GET_BOUQUET_STATUS = "GET_BOUQUET_STATUS";
export const GET_BOUQUET_STATUS_SUCCESS = "GET_BOUQUET_STATUS_SUCCESS";
export const GET_BOUQUET_STATUS_FAIL = "GET_BOUQUET_STATUS_FAIL";

export const GET_BOUQUET_BOXTYPE = "GET_BOUQUET_BOXTYPE";
export const GET_BOUQUET_BOXTYPE_SUCCESS = "GET_BOUQUET_BOXTYPE_SUCCESS";
export const GET_BOUQUET_BOXTYPE_FAIL = "GET_BOUQUET_BOXTYPE_FAIL";

export const GET_BOUQUEX = "GET_BOUQUEX";
export const GET_BOUQUEX_SUCCESS = "GET_BOUQUEX_SUCCESS";
export const GET_BOUQUEX_FAIL = "GET_BOUQUEX_FAIL";

export const GET_RECHARGEPERIOD = "GET_RECHARGEPERIOD";
export const GET_RECHARGEPERIOD_SUCCESS = "GET_RECHARGEPERIOD_SUCCESS";
export const GET_RECHARGEPERIOD_FAIL = "GET_RECHARGEPERIOD_FAIL";

export const GET_BOUQUET_TAXLIST = "GET_BOUQUET_TAXLIST";
export const GET_BOUQUET_TAXLIST_SUCCESS = "GET_BOUQUET_TAXLIST_SUCCESS";
export const GET_BOUQUET_TAXLIST_FAIL = "GET_BOUQUET_TAXLIST_FAIL";

export const GET_ALACARTECHANNELS = "GET_ALACARTECHANNELS";
export const GET_ALACARTECHANNELS_SUCCESS = "GET_ALACARTECHANNELS_SUCCESS";
export const GET_ALACARTECHANNELS_FAIL = "GET_ALACARTECHANNELS_FAIL";

export const GET_BOUQUET_PACKAGES = "GET_BOUQUET_PACKAGES";
export const GET_BOUQUET_PACKAGES_SUCCESS = "GET_BOUQUET_PACKAGES_SUCCESS";
export const GET_BOUQUET_PACKAGES_FAIL = "GET_BOUQUET_PACKAGES_FAIL";

export const GET_OPERATOR_FORBOUQUET = "GET_OPERATOR_FORBOUQUET";
export const GET_OPERATOR_FORBOUQUET_SUCCESS =
  "GET_OPERATOR_FORBOUQUET_SUCCESS";
export const GET_OPERATOR_FORBOUQUET_FAIL = "GET_OPERATOR_FORBOUQUET_FAIL";

export const UPDATE_BOUQUET_CURRENT_PAGE = "UPDATE_BOUQUET_CURRENT_PAGE";
