export const GET_BOUQUET = "GET_BOUQUET";
export const GET_BOUQUET_SUCCESS = "GET_BOUQUET_SUCCESS";
export const GET_BOUQUET_FAIL = "GET_BOUQUET_FAIL";

export const ADD_BOUQUET = "ADD_BOUQUET";
export const ADD_BOUQUET_SUCCESS = "ADD_BOUQUET_SUCCESS";
export const ADD_BOUQUET_FAIL = "ADD_BOUQUET_FAIL";
