/* CUSTOMER USERS */
export const GET_STATEUSERS = "GET_STATEUSERS"
export const GET_STATEUSERS_SUCCESS = "GET_STATEUSERS_SUCCESS"
export const GET_STATEUSERS_FAIL = "GET_STATEUSERS_FAIL"

export const UPDATE_STATEUSERS_CURRENT_PAGE = "UPDATE_STATEUSERS_CURRENT_PAGE";