export const GET_SUBLOCATION = "GET_SUBLOCATION";
export const GET_SUBLOCATION_SUCCESS = "GET_SUBLOCATION_SUCCESS";
export const GET_SUBLOCATION_FAIL = "GET_SUBLOCATION_FAIL";

export const ADD_SUBLOCATION = "ADD_SUBLOCATION";
export const ADD_SUBLOCATION_SUCCESS = "ADD_SUBLOCATION_SUCCESS";
export const ADD_SUBLOCATION_FAIL = "ADD_SUBLOCATION_FAIL";

export const UPDATE_SUBLOCATION = "UPDATE_SUBLOCATION";
export const UPDATE_SUBLOCATION_SUCCESS = "UPDATE_SUBLOCATION_SUCCESS";
export const UPDATE_SUBLOCATION_FAIL = "UPDATE_SUBLOCATION_FAIL";

export const GET_LOCATION_ONSUBLOCATION = "GET_LOCATION_ONSUBLOCATION";
export const GET_LOCATION_ONSUBLOCATION_SUCCESS =
  "GET_LOCATION_ONSUBLOCATION_SUCCESS";
export const GET_LOCATION_ONSUBLOCATION_FAIL =
  "GET_LOCATION_ONSUBLOCATION_FAIL";

export const GET_SINGLE_SUBLOCATION = "GET_SINGLE_SUBLOCATION";
export const GET_SINGLE_SUBLOCATION_SUCCESS = "GET_SINGLE_SUBLOCATION_SUCCESS";
export const GET_SINGLE_SUBLOCATION_FAIL = "GET_SINGLE_SUBLOCATION_FAIL";

export const UPDATE_SUBLOCATION_CURRENT_PAGE =
  "UPDATE_SUBLOCATION_CURRENT_PAGE";
