export const GET_SUBLOCATION = "GET_SUBLOCATION";
export const GET_SUBLOCATION_SUCCESS = "GET_SUBLOCATION_SUCCESS";
export const GET_SUBLOCATION_FAIL = "GET_SUBLOCATION_FAIL";

export const ADD_SUBLOCATION = "ADD_SUBLOCATION";
export const ADD_SUBLOCATION_SUCCESS = "ADD_SUBLOCATION_SUCCESS";
export const ADD_SUBLOCATION_FAIL = "ADD_SUBLOCATION_FAIL";
