export const GET_CONNECTIONSCHEME = "GET_CONNECTIONSCHEME";
export const GET_CONNECTIONSCHEME_SUCCESS = "GET_CONNECTIONSCHEME_SUCCESS";
export const GET_CONNECTIONSCHEME_FAIL = "GET_CONNECTIONSCHEME_FAIL";

export const ADD_CONNECTIONSCHEME = "ADD_CONNECTIONSCHEME";
export const ADD_CONNECTIONSCHEME_SUCCESS = "ADD_CONNECTIONSCHEME_SUCCESS";
export const ADD_CONNECTIONSCHEME_FAIL = "ADD_CONNECTIONSCHEME_FAIL";
