export const GET_CONNECTIONSCHEME = "GET_CONNECTIONSCHEME";
export const GET_CONNECTIONSCHEME_SUCCESS = "GET_CONNECTIONSCHEME_SUCCESS";
export const GET_CONNECTIONSCHEME_FAIL = "GET_CONNECTIONSCHEME_FAIL";

export const ADD_CONNECTIONSCHEME = "ADD_CONNECTIONSCHEME";
export const ADD_CONNECTIONSCHEME_SUCCESS = "ADD_CONNECTIONSCHEME_SUCCESS";
export const ADD_CONNECTIONSCHEME_FAIL = "ADD_CONNECTIONSCHEME_FAIL";

export const GET_CONNECTIONSCHEME_BOXTYPE = "GET_CONNECTIONSCHEME_BOXTYPE";
export const GET_CONNECTIONSCHEME_BOXTYPE_SUCCESS =
  "GET_CONNECTIONSCHEME_BOXTYPE_SUCCESS";
export const GET_CONNECTIONSCHEME_BOXTYPE_FAIL =
  "GET_CONNECTIONSCHEME_BOXTYPE_FAIL";

export const GET_CONNECTIONSCHEME_STATUS = "GET_CONNECTIONSCHEME_STATUS";
export const GET_CONNECTIONSCHEME_STATUS_SUCCESS =
  "GET_CONNECTIONSCHEME_STATUS_SUCCESS";
export const GET_CONNECTIONSCHEME_STATUS_FAIL =
  "GET_CONNECTIONSCHEME_STATUS_FAIL";

export const UPDATE_CONNECTIONSCHEME = "UPDATE_CONNECTIONSCHEME";
export const UPDATE_CONNECTIONSCHEME_SUCCESS =
  "UPDATE_CONNECTIONSCHEME_SUCCESS";
export const UPDATE_CONNECTIONSCHEME_FAIL = "UPDATE_CONNECTIONSCHEME_FAIL";
