export const GET_CONNECTIONSCHEME = "GET_CONNECTIONSCHEME";
export const GET_CONNECTIONSCHEME_SUCCESS = "GET_CONNECTIONSCHEME_SUCCESS";
export const GET_CONNECTIONSCHEME_FAIL = "GET_CONNECTIONSCHEME_FAIL";
