export const GET_REGIONALOFFICE = "GET_REGIONALOFFICE";
export const GET_REGIONALOFFICE_SUCCESS = "GET_REGIONALOFFICE_SUCCESS";
export const GET_REGIONALOFFICE_FAIL = "GET_REGIONALOFFICE_FAIL";

export const ADD_NEW_REGIONALOFFICE = "ADD_NEW_REGIONALOFFICE";
export const ADD_REGIONALOFFICE_SUCCESS = "ADD_REGIONALOFFICE_SUCCESS";
export const ADD_REGIONALOFFICE_FAIL = "ADD_REGIONALOFFICE_FAIL";

export const UPDATE_REGIONALOFFICE = "UPDATE_REGIONALOFFICE";
export const UPDATE_REGIONALOFFICE_SUCCESS = "UPDATE_REGIONALOFFICE_SUCCESS";
export const UPDATE_REGIONALOFFICE_FAIL = "UPDATE_REGIONALOFFICE_FAIL";
export const SET_PER_PAGE = "SET_PER_PAGE";
export const SET_CURRENT_PAGE = "SET_CURRENT_PAGE";

export const UPDATE_REGIONALOFFICES_CURRENT_PAGE =
  "UPDATE_REGIONALOFFICES_CURRENT_PAGE";
