/* CUSTOMER USERS */
export const GET_CUSTOMERUSERS = "GET_CUSTOMERUSERS"
export const GET_CUSTOMERUSERS_SUCCESS = "GET_CUSTOMERUSERS_SUCCESS"
export const GET_CUSTOMERUSERS_FAIL = "GET_CUSTOMERUSERS_FAIL"

