/* CUSTOMER USERS */
export const GET_CUSTOMERUSERS = "GET_CUSTOMERUSERS";
export const GET_CUSTOMERUSERS_SUCCESS = "GET_CUSTOMERUSERS_SUCCESS";
export const GET_CUSTOMERUSERS_FAIL = "GET_CUSTOMERUSERS_FAIL";

export const UPDATE_CUSTOMERUSER = "UPDATE_CUSTOMERUSER";
export const UPDATE_CUSTOMERUSER_SUCCESS = "UPDATE_CUSTOMERUSER_SUCCESS";
export const UPDATE_CUSTOMERUSER_FAIL = "UPDATE_CUSTOMERUSER_FAIL";
