export const GET_INVENTORYSTOCK = "GET_INVENTORYSTOCK";
export const GET_INVENTORYSTOCK_SUCCESS = "GET_INVENTORYSTOCK_SUCCESS";
export const GET_INVENTORYSTOCK_FAIL = "GET_INVENTORYSTOCK_FAIL";

export const GET_INVENTORYSTOCK_STB = "GET_INVENTORYSTOCK_STB";
export const GET_INVENTORYSTOCK_STB_SUCCESS = "GET_INVENTORYSTOCK_STB_SUCCESS";
export const GET_INVENTORYSTOCK_STB_FAIL = "GET_INVENTORYSTOCK_STB_FAIL";

export const GET_INVENTORYSTOCK_PAIRING = "GET_INVENTORYSTOCK_PAIRING";
export const GET_INVENTORYSTOCK_PAIRING_SUCCESS =
  "GET_INVENTORYSTOCK_PAIRING_SUCCESS";
export const GET_INVENTORYSTOCK_PAIRING_FAIL =
  "GET_INVENTORYSTOCK_PAIRING_FAIL";
