export const GET_INVENTORYSTOCK_SMARTCARD = "GET_INVENTORYSTOCK_SMARTCARD";
export const GET_INVENTORYSTOCK_SMARTCARD_SUCCESS =
  "GET_INVENTORYSTOCK_SUCCESS_SMARTCARD";
export const GET_INVENTORYSTOCK_SMARTCARD_FAIL =
  "GET_INVENTORYSTOCK_SMARTCARD_FAIL";

export const GET_INVENTORYSTOCK_STB = "GET_INVENTORYSTOCK_STB";
export const GET_INVENTORYSTOCK_STB_SUCCESS = "GET_INVENTORYSTOCK_STB_SUCCESS";
export const GET_INVENTORYSTOCK_STB_FAIL = "GET_INVENTORYSTOCK_STB_FAIL";

export const GET_INVENTORYSTOCK_PAIRING = "GET_INVENTORYSTOCK_PAIRING";
export const GET_INVENTORYSTOCK_PAIRING_SUCCESS =
  "GET_INVENTORYSTOCK_PAIRING_SUCCESS";
export const GET_INVENTORYSTOCK_PAIRING_FAIL =
  "GET_INVENTORYSTOCK_PAIRING_FAIL";

export const UPDATE_STOCKPAIRING_CURRENT_PAGE =
  "UPDATE_STOCKPAIRING_CURRENT_PAGE";

export const UPDATE_INVENTORYSTOCK_STB = "UPDATE_INVENTORYSTOCK_STB";
export const UPDATE_INVENTORYSTOCK_STB_SUCCESS =
  "UPDATE_INVENTORYSTOCK_STB_SUCCESS";
export const UPDATE_INVENTORYSTOCK_STB_FAIL = "UPDATE_INVENTORYSTOCK_STB_FAIL";

export const GET_INVENTORYSTOCK_SC_CASTYPE = "GET_INVENTORYSTOCK_SC_CASTYPE";
export const GET_INVENTORYSTOCK_SC_CASTYPE_SUCCESS =
  "GET_INVENTORYSTOCK_SC_CASTYPE_SUCCESS";
export const GET_INVENTORYSTOCK_SC_CASTYPE_FAIL =
  "GET_INVENTORYSTOCK_SC_CASTYPE_FAIL";

export const GET_INVENTORYSTOCK_SC_WAREHOUSE =
  "GET_INVENTORYSTOCK_SC_WAREHOUSE";
export const GET_INVENTORYSTOCK_SC_WAREHOUSE_SUCCESS =
  "GET_INVENTORYSTOCK_SC_WAREHOUSE_SUCCESS";
export const GET_INVENTORYSTOCK_SC_WAREHOUSE_FAIL =
  "GET_INVENTORYSTOCK_SC_WAREHOUSE_FAIL";

export const GET_INVENTORYSTOCK_SC_STATETYPE =
  "GET_INVENTORYSTOCK_SC_STATETYPE";
export const GET_INVENTORYSTOCK_SC_STATETYPE_SUCCESS =
  "GET_INVENTORYSTOCK_SC_STATETYPE_SUCCESS";
export const GET_INVENTORYSTOCK_SC_STATETYPE_FAIL =
  "GET_INVENTORYSTOCK_SC_STATETYPE_FAIL";

export const GET_INVENTORYSTOCK_SC_INVENTORYSTATE =
  "GET_INVENTORYSTOCK_SC_INVENTORYSTATE";
export const GET_INVENTORYSTOCK_SC_INVENTORYSTATE_SUCCESS =
  "GET_INVENTORYSTOCK_SC_INVENTORYSTATE_SUCCESS";
export const GET_INVENTORYSTOCK_SC_INVENTORYSTATE_FAIL =
  "GET_INVENTORYSTOCK_SC_INVENTORYSTATE_FAIL";

export const ADD_INVENTORYSTOCK_SMARTCARD = "ADD_INVENTORYSTOCK_SMARTCARD";
export const ADD_INVENTORYSTOCK_SMARTCARD_SUCCESS =
  "ADD_INVENTORYSTOCK_SMARTCARD_SUCCESS";
export const ADD_INVENTORYSTOCK_SMARTCARD_FAIL =
  "ADD_INVENTORYSTOCK_SMARTCARD_FAIL";

export const GET_INVENTORYSTOCK_SC_BRAND1 = "GET_INVENTORYSOCK_SC_BRAND1";
export const GET_INVENTORYSTOCK_SC_BRAND1_SUCCESS =
  "GET_INVENTORYSOCK_SC_BRAND1_SUCCESS";
export const GET_INVENTORYSTOCK_SC_BRAND1_FAIL =
  "GET_INVENTORYSOCK_SC_BRAND1_FAIL";

export const GET_INVENTORYSTOCK_SC_BRAND2 = "GET_INVENTORYSOCK_SC_BRAND2";
export const GET_INVENTORYSTOCK_SC_BRAND2_SUCCESS =
  "GET_INVENTORYSOCK_SC_BRAND2_SUCCESS";
export const GET_INVENTORYSTOCK_SC_BRAND2_FAIL =
  "GET_INVENTORYSOCK_SC_BRAND2_FAIL";
