export const GET_INVENTORYSTOCK = "GET_INVENTORYSTOCK";
export const GET_INVENTORYSTOCK_SUCCESS = "GET_INVENTORYSTOCK_SUCCESS";
export const GET_INVENTORYSTOCK_FAIL = "GET_INVENTORYSTOCK_FAIL";

export const GET_INVENTORYSTOCK_STB = "GET_INVENTORYSTOCK_STB";
export const GET_INVENTORYSTOCK_STB_SUCCESS = "GET_INVENTORYSTOCK_STB_SUCCESS";
export const GET_INVENTORYSTOCK_STB_FAIL = "GET_INVENTORYSTOCK_STB_FAIL";

export const GET_INVENTORYSTOCK_PAIRING = "GET_INVENTORYSTOCK_PAIRING";
export const GET_INVENTORYSTOCK_PAIRING_SUCCESS =
  "GET_INVENTORYSTOCK_PAIRING_SUCCESS";
export const GET_INVENTORYSTOCK_PAIRING_FAIL =
  "GET_INVENTORYSTOCK_PAIRING_FAIL";

export const GET_INVENTORYFAULTY_SMARTCARD = "GET_INVENTORYFAULTY_SMARTCARD";
export const GET_INVENTORYFAULTY_SMARTCARD_SUCCESS =
  "GET_INVENTORYFAULTY_SMARTCARD_SUCCESS";
export const GET_INVENTORYFAULTY_SMARTCARD_FAIL =
  "GET_INVENTORYFAULTY_SMARTCARD_FAIL";

export const GET_INVENTORYFAULTY_STB = "GET_INVENTORYFAULTY_STB";
export const GET_INVENTORYFAULTY_STB_SUCCESS =
  "GET_INVENTORYFAULTY_STB_SUCCESS";
export const GET_INVENTORYFAULTY_STB_FAIL = "GET_INVENTORYFAULTY_STB_FAIL";

export const GET_INVENTORYFAULTY_PAIRING = "GET_INVENTORYFAULTY_PAIRING";
export const GET_INVENTORYFAULTY_PAIRING_SUCCESS =
  "GET_INVENTORYFAULTY_PAIRING_SUCCESS";
export const GET_INVENTORYFAULTY_PAIRING_FAIL =
  "GET_INVENTORYFAULTY_PAIRING_FAIL";

export const GET_INVENTORYBLACKLISTED_SMARTCARD =
  "GET_INVENTORYBLACKLISTED_SMARTCARD";
export const GET_INVENTORYBLACKLISTED_SMARTCARD_SUCCESS =
  "GET_INVENTORYBLACKLISTED_SMARTCARD_SUCCESS";
export const GET_INVENTORYBLACKLISTED_SMARTCARD_FAIL =
  "GET_INVENTORYBLACKLISTED_SMARTCARD_FAIL";

export const GET_INVENTORYBLACKLISTED_STB = "GET_INVENTORYBLACKLISTED_STB";
export const GET_INVENTORYBLACKLISTED_STB_SUCCESS =
  "GET_INVENTORYBLACKLISTED_STB_SUCCESS";
export const GET_INVENTORYBLACKLISTED_STB_FAIL =
  "GET_INVENTORYBLACKLISTED_STB_FAIL";

export const GET_INVENTORYBLACKLISTED_PAIRING =
  "GET_INVENTORYBLACKLISTED_PAIRING";
export const GET_INVENTORYBLACKLISTED_PAIRING_SUCCESS =
  "GET_INVENTORYBLACKLISTED_PAIRING_SUCCESS";
export const GET_INVENTORYBLACKLISTED_PAIRING_FAIL =
  "GET_INVENTORYBLACKLISTED_PAIRING_FAIL";

export const GET_INVENTORYALLOTTED_SMARTCARD =
  "GET_INVENTORYALLOTTED_SMARTCARD";
export const GET_INVENTORYALLOTTED_SMARTCARD_SUCCESS =
  "GET_INVENTORYALLOTTED_SMARTCARD_SUCCESS";
export const GET_INVENTORYALLOTTED_SMARTCARD_FAIL =
  "GET_INVENTORYFAULTY_SMARTCARD_FAIL";

export const GET_INVENTORYALLOTTED_STB = "GET_INVENTORYALLOTTED_STB";
export const GET_INVENTORYALLOTTED_STB_SUCCESS =
  "GET_INVENTORYALLOTTED_STB_SUCCESS";
export const GET_INVENTORYALLOTTED_STB_FAIL = "GET_INVENTORYALLOTTED_STB_FAIL";

export const GET_INVENTORYALLOTTED_PAIRING = "GET_INVENTORYALLOTTED_PAIRING";
export const GET_INVENTORYALLOTTED_PAIRING_SUCCESS =
  "GET_INVENTORYALLOTTED_PAIRING_SUCCESS";
export const GET_INVENTORYALLOTTED_PAIRING_FAIL =
  "GET_INVENTORYALLOTTED_PAIRING_FAIL";

export const UPDATE_STOCKPAIRING_CURRENT_PAGE =
  "UPDATE_STOCKPAIRING_CURRENT_PAGE";
export const UPDATE_FAULTYPAIRING_CURRENT_PAGE =
  "UPDATE_FAULTYPAIRING_CURRENT_PAGE";
export const UPDATE_ALLOTTEDPAIRING_CURRENT_PAGE =
  "UPDATE_ALLOTTEDPAIRING_CURRENT_PAGE";
