/* GESIGNATION*/
export const GET_DESIGNATION = "GET_DESIGNATION";
export const GET_DESIGNATION_SUCCESS = "GET_DESIGNATION_SUCCESS";
export const GET_DESIGNATION_FAIL = "GET_DESIGNATION_FAIL";

export const GET_DESIGNATION_TYPE = "GET_DESIGNATION_TYPE";
export const GET_DESIGNATION_TYPE_SUCCESS = "GET_DESIGNATION_TYPE_SUCCESS";
export const GET_DESIGNATION_TYPE_FAIL = "GET_DESIGNATION_TYPE_FAIL";

export const GET_DESIGNATION_PARENT = "GET_DESIGNATION_PARENT";
export const GET_DESIGNATION_PARENT_SUCCESS = "GET_DESIGNATION_PARENT_SUCCESS";
export const GET_DESIGNATION_PARENT_FAIL = "GET_DESIGNATION_PARENT_FAIL";

export const GET_DESIGNATION_STATUS = "GET_DESIGNATION_STATUS";
export const GET_DESIGNATION_STATUS_SUCCESS = "GET_DESIGNATION_STATUS_SUCCESS";
export const GET_DESIGNATION_STATUS_FAIL = "GET_DESIGNATION_STATUS_FAIL";
export const ADD_NEW_DESIGNATION = "ADD_NEW_DESIGNATION";
export const ADD_DESIGNATION_SUCCESS = "ADD_DESIGNATION_SUCCESS";
export const ADD_DESIGNATION_FAIL = "ADD_DESIGNATION_FAIL";
