/* GESIGNATION*/
export const GET_DESIGNATION = "GET_DESIGNATION";
export const GET_DESIGNATION_SUCCESS = "GET_DESIGNATION_SUCCESS";
export const GET_DESIGNATION_FAIL = "GET_DESIGNATION_FAIL";

export const GET_DESIGNATION_STATUS = "GET_DESIGNATION_STATUS";
export const GET_DESIGNATION_STATUS_SUCCESS = "GET_DESIGNATION_STATUS_SUCCESS";
export const GET_DESIGNATION_STATUS_FAIL = "GET_DESIGNATION_STATUS_FAIL";

export const ADD_NEW_DESIGNATION = "ADD_NEW_DESIGNATION";
export const ADD_DESIGNATION_SUCCESS = "ADD_DESIGNATION_SUCCESS";
export const ADD_DESIGNATION_FAIL = "ADD_DESIGNATION_FAIL";
