/* CUSTOMER USERS */
export const GET_BROADCASTER = "GET_BROADCASTER";
export const GET_BROADCASTER_SUCCESS = "GET_BROADCASTER_SUCCESS";
export const GET_BROADCASTER_FAIL = "GET_BROADCASTER_FAIL";

export const GET_BROADCASTER_STATUS = "GET_BROADCASTER_STATUS";
export const GET_BROADCASTER_STATUS_SUCCESS = "GET_BROADCASTER_STATUS_SUCCESS";
export const GET_BROADCASTER_STATUS_FAIL = "GET_BROADCASTER_STATUS_FAIL";

export const ADD_NEW_BROADCASTER =
    "ADD_NEW_BROADCASTER";
export const ADD_BROADCASTER_SUCCESS =
    "ADD_BROADCASTER_SUCCESS";
export const ADD_BROADCASTER_FAIL =
    "ADD_BROADCASTER_FAIL";

export const UPDATE_BROADCASTER = "UPDATE_BROADCASTER";
export const UPDATE_BROADCASTER_SUCCESS = "UPDATE_BROADCASTER_SUCCESS";
export const UPDATE_BROADCASTER_FAIL = "UPDATE_BROADCASTER_FAIL";