/* CUSTOMER USERS */
export const GET_BROADCASTER = "GET_BROADCASTER";
export const GET_BROADCASTER_SUCCESS = "GET_BROADCASTER_SUCCESS";
export const GET_BROADCASTER_FAIL = "GET_BROADCASTER_FAIL";

export const ADD_NEW_BROADCASTER =
    "ADD_NEW_BROADCASTER";
export const ADD_BROADCASTER_SUCCESS =
    "ADD_BROADCASTER_SUCCESS";
export const ADD_BROADCASTER_FAIL =
    "ADD_BROADCASTER_FAIL";
