/* CUSTOMER USERS */
export const GET_DOCUMENTUPLOADPOLICY = "GET_DOCUMENTUPLOADPOLICY"
export const GET_DOCUMENTUPLOADPOLICY_SUCCESS = "GET_DOCUMENTUPLOADPOLICY_SUCCESS"
export const GET_DOCUMENTUPLOADPOLICY_FAIL = "GET_DOCUMENTUPLOADPOLICY_FAIL"

export const ADD_NEW_DOCUMENTUPLOADPOLICY =
    "ADD_NEW_DOCUMENTUPLOADPOLICY";
export const ADD_DOCUMENTUPLOADPOLICY_SUCCESS =
    "ADD_DOCUMENTUPLOADPOLICY_SUCCESS";
export const ADD_DOCUMENTUPLOADPOLICY_FAIL =
    "ADD_DOCUMENTUPLOADPOLICY_FAIL";
