/* CUSTOMER USERS */
export const GET_DOCUMENTUPLOADPOLICY = "GET_DOCUMENTUPLOADPOLICY"
export const GET_DOCUMENTUPLOADPOLICY_SUCCESS = "GET_DOCUMENTUPLOADPOLICY_SUCCESS"
export const GET_DOCUMENTUPLOADPOLICY_FAIL = "GET_DOCUMENTUPLOADPOLICY_FAIL"

