/* CUSTOMER USERS */
export const GET_BROADCASTERBOUQUETLIST = "GET_BROADCASTERBOUQUETLIST";
export const GET_BROADCASTERBOUQUETLIST_SUCCESS =
  "GET_BROADCASTERBOUQUETLIST_SUCCESS";
export const GET_BROADCASTERBOUQUETLIST_FAIL =
  "GET_BROADCASTERBOUQUETLIST_FAIL";

export const ADD_NEW_BROADCASTERBOUQUETLIST =
  "ADD_NEW_BROADCASTERBOUQUETLIST";
export const ADD_BROADCASTERBOUQUETLIST_SUCCESS =
  "ADD_BROADCASTERBOUQUETLIST_SUCCESS";
export const ADD_BROADCASTERBOUQUETLIST_FAIL =
  "ADD_BROADCASTERBOUQUETLIST_FAIL";

export const GET_BROADCASTERBOUQUETLIST_DEFINITION = "GET_BROADCASTERBOUQUETLIST_DEFINITION";
export const GET_BROADCASTERBOUQUETLIST_DEFINITION_SUCCESS = "GET_BROADCASTERBOUQUETLIST_DEFINITION_SUCCESS";
export const GET_BROADCASTERBOUQUETLIST_DEFINITION_FAIL = "GET_BROADCASTERBOUQUETLIST_DEFINITION_FAIL";

export const GET_BROADCASTERBOUQUETLIST_STATUS = "GET_BROADCASTERBOUQUETLIST_STATUS";
export const GET_BROADCASTERBOUQUETLIST_STATUS_SUCCESS = "GET_BROADCASTERBOUQUETLIST_STATUS_SUCCESS";
export const GET_BROADCASTERBOUQUETLIST_STATUS_FAIL = "GET_BROADCASTERBOUQUETLIST_STATUS_FAIL";

export const GET_BROADCASTERBOUQUETLIST_TYPE = "GET_BROADCASTERBOUQUETLIST_TYPE";
export const GET_BROADCASTERBOUQUETLIST_TYPE_SUCCESS = "GET_BROADCASTERBOUQUETLIST_TYPE_SUCCESS";
export const GET_BROADCASTERBOUQUETLIST_TYPE_FAIL = "GET_BROADCASTERBOUQUETLIST_TYPE_FAIL";

export const GET_BROADCASTERBOUQUETLIST_ADDCHANNELS = "GET_BROADCASTERBOUQUETLIST_ADDCHANNELS";
export const GET_BROADCASTERBOUQUETLIST_ADDCHANNELS_SUCCESS = "GET_BROADCASTERBOUQUETLIST_ADDCHANNELS_SUCCESS";
export const GET_BROADCASTERBOUQUETLIST_ADDCHANNELS_FAIL = "GET_BROADCASTERBOUQUETLIST_ADDCHANNELS_FAIL";

export const GET_BROADCASTERBOUQUETLIST_BROADCASTER = "GET_BROADCASTERBOUQUETLIST_BROADCASTER";
export const GET_BROADCASTERBOUQUETLIST_BROADCASTER_SUCCESS = "GET_BROADCASTERBOUQUETLIST_BROADCASTER_SUCCESS";
export const GET_BROADCASTERBOUQUETLIST_BROADCASTER_FAIL = "GET_BROADCASTERBOUQUETLIST_BROADCASTER_FAIL";

export const UPDATE_BROADCASTERBOUQUETLIST = "UPDATE_BROADCASTERBOUQUETLIST";
export const UPDATE_BROADCASTERBOUQUETLIST_SUCCESS = "UPDATE_BROADCASTERBOUQUETLIST_SUCCESS";
export const UPDATE_BROADCASTERBOUQUETLIST_FAIL = "UPDATE_BROADCASTERBOUQUETLIST_FAIL";

export const UPDATE_BROADCASTERBOUQUETLIST_CURRENT_PAGE = "UPDATE_BROADCASTERBOUQUETLIST_CURRENT_PAGE";