/* CUSTOMER USERS */
export const GET_BROADCASTERBOUQUETLIST = "GET_BROADCASTERBOUQUETLIST";
export const GET_BROADCASTERBOUQUETLIST_SUCCESS =
  "GET_BROADCASTERBOUQUETLIST_SUCCESS";
export const GET_BROADCASTERBOUQUETLIST_FAIL =
  "GET_BROADCASTERBOUQUETLIST_FAIL";

export const ADD_NEW_BROADCASTERBOUQUETLIST =
  "ADD_NEW_BROADCASTERBOUQUETLIST";
export const ADD_BROADCASTERBOUQUETLIST_SUCCESS =
  "ADD_BROADCASTERBOUQUETLIST_SUCCESS";
export const ADD_BROADCASTERBOUQUETLIST_FAIL =
  "ADD_BROADCASTERBOUQUETLIST_FAIL";
