/* CUSTOMER USERS */
export const GET_BROADCASTERBOUQUETLIST = "GET_BROADCASTERBOUQUETLIST";
export const GET_BROADCASTERBOUQUETLIST_SUCCESS =
  "GET_BROADCASTERBOUQUETLIST_SUCCESS";
export const GET_BROADCASTERBOUQUETLIST_FAIL =
  "GET_BROADCASTERBOUQUETLIST_FAIL";
