/* CUSTOMER USERS */
export const GET_GENRELIST = "GET_GENRELIST";
export const GET_GENRELIST_SUCCESS = "GET_GENRELIST_SUCCESS";
export const GET_GENRELIST_FAIL = "GET_GENRELIST_FAIL";

export const ADD_NEW_GENRELIST =
    "ADD_NEW_GENRELIST";
export const ADD_GENRELIST_SUCCESS =
    "ADD_GENRELIST_SUCCESS";
export const ADD_GENRELIST_FAIL =
    "ADD_GENRELIST_FAIL";
