/* CUSTOMER USERS */
export const GET_GENRELIST = "GET_GENRELIST";
export const GET_GENRELIST_SUCCESS = "GET_GENRELIST_SUCCESS";
export const GET_GENRELIST_FAIL = "GET_GENRELIST_FAIL";

export const GET_GENRELIST_STATUS = "GET_GENRELIST_STATUS";
export const GET_GENRELIST_STATUS_SUCCESS = "GET_GENRELIST_STATUS_SUCCESS";
export const GET_GENRELIST_STATUS_FAIL = "GET_GENRELIST_STATUS_FAIL";

export const UPDATE_GENRELIST = "UPDATE_GENRELIST";
export const UPDATE_GENRELIST_SUCCESS = "UPDATE_GENRELIST_SUCCESS";
export const UPDATE_GENRELIST_FAIL = "UPDATE_GENRELIST_FAIL";

export const ADD_NEW_GENRELIST =
    "ADD_NEW_GENRELIST";
export const ADD_GENRELIST_SUCCESS =
    "ADD_GENRELIST_SUCCESS";
export const ADD_GENRELIST_FAIL =
    "ADD_GENRELIST_FAIL";
