export const GET_INVENTORYALLOTTED_SMARTCARD =
  "GET_INVENTORYALLOTTED_SMARTCARD";
export const GET_INVENTORYALLOTTED_SMARTCARD_SUCCESS =
  "GET_INVENTORYALLOTTED_SMARTCARD_SUCCESS";
export const GET_INVENTORYALLOTTED_SMARTCARD_FAIL =
  "GET_INVENTORYFAULTY_SMARTCARD_FAIL";

export const GET_INVENTORYALLOTTED_STB = "GET_INVENTORYALLOTTED_STB";
export const GET_INVENTORYALLOTTED_STB_SUCCESS =
  "GET_INVENTORYALLOTTED_STB_SUCCESS";
export const GET_INVENTORYALLOTTED_STB_FAIL = "GET_INVENTORYALLOTTED_STB_FAIL";

export const GET_INVENTORYALLOTTED_PAIRING = "GET_INVENTORYALLOTTED_PAIRING";
export const GET_INVENTORYALLOTTED_PAIRING_SUCCESS =
  "GET_INVENTORYALLOTTED_PAIRING_SUCCESS";
export const GET_INVENTORYALLOTTED_PAIRING_FAIL =
  "GET_INVENTORYALLOTTED_PAIRING_FAIL";

export const UPDATE_ALLOTTEDPAIRING_CURRENT_PAGE =
  "UPDATE_ALLOTTEDPAIRING_CURRENT_PAGE";

export const GET_INVENTORYALLOTTED_SMARTCARDLIST =
  "GET_INVENTORYALLOTTED_SMARTCARDLIST";
export const GET_INVENTORYALLOTTED_SMARTCARDLIST_SUCCESS =
  "GET_INVENTORYALLOTTED_SMARTCARDLIST_SUCCESS";
export const GET_INVENTORYALLOTTED_SMARTCARDLIST_FAIL =
  "GET_INVENTORYFAULTY_SMARTCARDLIST_FAIL";

export const GET_INVENTORYALLOTTED_USERTYPE = "GET_INVENTORYALLOTTED_USERTYPE";
export const GET_INVENTORYALLOTTED_USERTYPE_SUCCESS =
  "GET_INVENTORYALLOTTED_USERTYPE_SUCCESS";
export const GET_INVENTORYALLOTTED_USERTYPE_FAIL =
  "GET_INVENTORYALLOTTED_USERTYPE_FAIL";

export const GET_INVENTORYALLOTTED_OPERATORLIST =
  "GET_INVENTORYALLOTTED_OPERATORLIST";
export const GET_INVENTORYALLOTTED_OPERATORLIST_SUCCESS =
  "GET_INVENTORYALLOTTED_OPERATORLIST_SUCCESS";
export const GET_INVENTORYALLOTTED_OPERATORLIST_FAIL =
  "GET_INVENTORYALLOTTED_OPERATORLIST_FAIL";

export const ALLOT_SMARTCARD = "ALLOT_SMARTCARD";
export const ALLOT_SMARTCARD_SUCCESS = "ALLOT_SMARTCARD_SUCCESS";
export const ALLOT_SMARTCARD_FAIL = "ALLOT_SMARTCARD_FAIL";

export const DEALLOT_SMARTCARD = "DEALLOT_SMARTCARD";
export const DEALLOT_SMARTCARD_SUCCESS = "DEALLOT_SMARTCARD_SUCCESS";
export const DEALLOT_SMARTCARD_FAIL = "DEALLOT_SMARTCARD_FAIL";

export const GET_INVENTORYALLOTTED_DISTRIBUTOR =
  "GET_INVENTORYALLOTTED_DISTRIBUTOR";
export const GET_INVENTORYALLOTTED_DISTRIBUTOR_SUCCESS =
  "GET_INVENTORYALLOTTED_DISTRIBUTOR_SUCCESS";
export const GET_INVENTORYALLOTTED_DISTRIBUTOR_FAIL =
  "GET_INVENTORYALLOTTED_DISTRIBUTOR_FAIL";

export const GET_INVENTORYALLOTTED_LCO = "GET_INVENTORYALLOTTED_LCO";
export const GET_INVENTORYALLOTTED_LCO_SUCCESS =
  "GET_INVENTORYALLOTTED_LCO_SUCCESS";
export const GET_INVENTORYALLOTTED_LCO_FAIL = "GET_INVENTORYALLOTTED_LCO_FAIL";

export const GET_INVENTORYALLOTTED_STBLIST = "GET_INVENTORYALLOTTED_STBLIST";
export const GET_INVENTORYALLOTTED_STBLIST_SUCCESS =
  "GET_INVENTORYALLOTTED_STBLIST_SUCCESS";
export const GET_INVENTORYALLOTTED_STBLIST_FAIL =
  "GET_INVENTORYALLOTTED_STBLIST_FAIL";

export const ALLOT_STB = "ALLOT_STB";
export const ALLOT_STB_SUCCESS = "ALLOT_STB_SUCCESS";
export const ALLOT_STB_FAIL = "ALLOT_STB_FAIL";

export const DEALLOT_STB = "DEALLOT_STB";
export const DEALLOT_STB_SUCCESS = "DEALLOT_STB_SUCCESS";
export const DEALLOT_STB_FAIL = "DEALLOT_STB_FAIL";

export const GET_INVENTORYALLOTTED_PAIRINGLIST =
  "GET_INVENTORYALLOTTED_PAIRINGLIST";
export const GET_INVENTORYALLOTTED_PAIRINGLIST_SUCCESS =
  "GET_INVENTORYALLOTTED_PAIRINGLIST_SUCCESS";
export const GET_INVENTORYALLOTTED_PAIRINGLIST_FAIL =
  "GET_INVENTORYALLOTTED_PAIRINGLIST_FAIL";

export const ALLOT_PAIRING = "ALLOT_PAIRING";
export const ALLOT_PAIRING_SUCCESS = "ALLOT_PAIRING_SUCCESS";
export const ALLOT_PAIRING_FAIL = "ALLOT_PAIRING_FAIL";

export const DEALLOT_PAIRING = "DEALLOT_PAIRING";
export const DEALLOT_PAIRING_SUCCESS = "DEALLOT_PAIRING_SUCCESS";
export const DEALLOT_PAIRING_FAIL = "DEALLOT_PAIRING_FAIL";

export const GET_INVENTORYALLOTTED_MATERIALSTATUS =
  "GET_INVENTORYALLOTTED_MATERIALSTATUS";
export const GET_INVENTORYALLOTTED_MATERIALSTATUS_SUCCESS =
  "GET_INVENTORYALLOTTED_MATERIALSTATUS_SUCCESS";
export const GET_INVENTORYALLOTTED_MATERIALSTATUS_FAIL =
  "GET_INVENTORYALLOTTED_MATERIALSTATUS_FAIL";

export const GET_INVENTORYALLOTTED_PAIRINGSTATUS =
  "GET_INVENTORYALLOTTED_PAIRINGSTATUS";
export const GET_INVENTORYALLOTTED_PAIRINGSTATUS_SUCCESS =
  "GET_INVENTORYALLOTTED_PAIRINGSTATUS_SUCCESS";
export const GET_INVENTORYALLOTTED_PAIRINGSTATUS_FAIL =
  "GET_INVENTORYALLOTTED_PAIRINGSTATUS_FAIL";

export const GET_INVENTORYALLOTTED_INVENTORYSTATEBYID =
  "GET_INVENTORYALLOTTED_INVENTORYSTATEBYID";
export const GET_INVENTORYALLOTTED_INVENTORYSTATEBYID_SUCCESS =
  "GET_INVENTORYALLOTTED_INVENTORYSTATEBYID_SUCCESS";
export const GET_INVENTORYALLOTTED_INVENTORYSTATEBYID_FAIL =
  "GET_INVENTORYALLOTTED_INVENTORYSTATEBYID_FAIL";
