export const GET_INVENTORYALLOTTED_SMARTCARD =
  "GET_INVENTORYALLOTTED_SMARTCARD";
export const GET_INVENTORYALLOTTED_SMARTCARD_SUCCESS =
  "GET_INVENTORYALLOTTED_SMARTCARD_SUCCESS";
export const GET_INVENTORYALLOTTED_SMARTCARD_FAIL =
  "GET_INVENTORYFAULTY_SMARTCARD_FAIL";

export const GET_INVENTORYALLOTTED_STB = "GET_INVENTORYALLOTTED_STB";
export const GET_INVENTORYALLOTTED_STB_SUCCESS =
  "GET_INVENTORYALLOTTED_STB_SUCCESS";
export const GET_INVENTORYALLOTTED_STB_FAIL = "GET_INVENTORYALLOTTED_STB_FAIL";

export const GET_INVENTORYALLOTTED_PAIRING = "GET_INVENTORYALLOTTED_PAIRING";
export const GET_INVENTORYALLOTTED_PAIRING_SUCCESS =
  "GET_INVENTORYALLOTTED_PAIRING_SUCCESS";
export const GET_INVENTORYALLOTTED_PAIRING_FAIL =
  "GET_INVENTORYALLOTTED_PAIRING_FAIL";

export const UPDATE_ALLOTTEDPAIRING_CURRENT_PAGE =
  "UPDATE_ALLOTTEDPAIRING_CURRENT_PAGE";
