export const GET_INVENTORYALLOTTED_SMARTCARD =
  "GET_INVENTORYALLOTTED_SMARTCARD";
export const GET_INVENTORYALLOTTED_SMARTCARD_SUCCESS =
  "GET_INVENTORYALLOTTED_SMARTCARD_SUCCESS";
export const GET_INVENTORYALLOTTED_SMARTCARD_FAIL =
  "GET_INVENTORYFAULTY_SMARTCARD_FAIL";

export const GET_INVENTORYALLOTTED_STB = "GET_INVENTORYALLOTTED_STB";
export const GET_INVENTORYALLOTTED_STB_SUCCESS =
  "GET_INVENTORYALLOTTED_STB_SUCCESS";
export const GET_INVENTORYALLOTTED_STB_FAIL = "GET_INVENTORYALLOTTED_STB_FAIL";

export const GET_INVENTORYALLOTTED_PAIRING = "GET_INVENTORYALLOTTED_PAIRING";
export const GET_INVENTORYALLOTTED_PAIRING_SUCCESS =
  "GET_INVENTORYALLOTTED_PAIRING_SUCCESS";
export const GET_INVENTORYALLOTTED_PAIRING_FAIL =
  "GET_INVENTORYALLOTTED_PAIRING_FAIL";

export const UPDATE_ALLOTTEDPAIRING_CURRENT_PAGE =
  "UPDATE_ALLOTTEDPAIRING_CURRENT_PAGE";

export const GET_INVENTORYALLOTTED_SMARTCARDLIST =
  "GET_INVENTORYALLOTTED_SMARTCARDLIST";
export const GET_INVENTORYALLOTTED_SMARTCARDLIST_SUCCESS =
  "GET_INVENTORYALLOTTED_SMARTCARDLIST_SUCCESS";
export const GET_INVENTORYALLOTTED_SMARTCARDLIST_FAIL =
  "GET_INVENTORYFAULTY_SMARTCARDLIST_FAIL";

export const GET_INVENTORYALLOTTED_USERTYPE = "GET_INVENTORYALLOTTED_USERTYPE";
export const GET_INVENTORYALLOTTED_USERTYPE_SUCCESS =
  "GET_INVENTORYALLOTTED_USERTYPE_SUCCESS";
export const GET_INVENTORYALLOTTED_USERTYPE_FAIL =
  "GET_INVENTORYALLOTTED_USERTYPE_FAIL";

export const GET_INVENTORYALLOTTED_OPERATORLIST =
  "GET_INVENTORYALLOTTED_OPERATORLIST";
export const GET_INVENTORYALLOTTED_OPERATORLIST_SUCCESS =
  "GET_INVENTORYALLOTTED_OPERATORLIST_SUCCESS";
export const GET_INVENTORYALLOTTED_OPERATORLIST_FAIL =
  "GET_INVENTORYALLOTTED_OPERATORLIST_FAIL";

export const ALLOT_SMARTCARD = "ALLOT_SMARTCARD";
export const ALLOT_SMARTCARD_SUCCESS = "ALLOT_SMARTCARD_SUCCESS";
export const ALLOT_SMARTCARD_FAIL = "ALLOT_SMARTCARD_FAIL";

export const DEALLOT_SMARTCARD = "DEALLOT_SMARTCARD";
export const DEALLOT_SMARTCARD_SUCCESS = "DEALLOT_SMARTCARD_SUCCESS";
export const DEALLOT_SMARTCARD_FAIL = "DEALLOT_SMARTCARD_FAIL";
