/* CUSTOMER USERS */
export const GET_GROUPPOLICY = "GET_GROUPPOLICY";
export const GET_GROUPPOLICY_SUCCESS = "GET_GROUPPOLICY_SUCCESS";
export const GET_GROUPPOLICY_FAIL = "GET_GROUPPOLICY_FAIL";

export const ADD_NEW_GROUPPOLICY = "ADD_NEW_GROUPPOLICY";
export const ADD_GROUPPOLICY_SUCCESS = "ADD_GROUPPOLICY_SUCCESS";
export const ADD_GROUPPOLICY_FAIL = "ADD_GROUPPOLICY_FAIL";
