/* CUSTOMER USERS */
export const GET_GROUPPOLICY = "GET_GROUPPOLICY";
export const GET_GROUPPOLICY_SUCCESS = "GET_GROUPPOLICY_SUCCESS";
export const GET_GROUPPOLICY_FAIL = "GET_GROUPPOLICY_FAIL";

export const ADD_NEW_GROUPPOLICY = "ADD_NEW_GROUPPOLICY";
export const ADD_GROUPPOLICY_SUCCESS = "ADD_GROUPPOLICY_SUCCESS";
export const ADD_GROUPPOLICY_FAIL = "ADD_GROUPPOLICY_FAIL";

export const GET_POLICY_TYPE = "GET_POLICY_TYPE";
export const GET_POLICY_TYPE_SUCCESS = "GET_POLICY_TYPE_SUCCESS";
export const GET_POLICY_TYPE_FAIL = "GET_POLICY_TYPE_FAIL";

export const GET_POLICY_ROLE = "GET_POLICY_ROLE";
export const GET_POLICY_ROLE_SUCCESS = "GET_POLICY_ROLE_SUCCESS";
export const GET_POLICY_ROLE_FAIL = "GET_POLICY_ROLE_FAIL";
