/* CUSTOMER USERS */
export const GET_USERHIERARCHY = "GET_USERHIERARCHY"
export const GET_USERHIERARCHY_SUCCESS = "GET_USERHIERARCHY_SUCCESS"
export const GET_USERHIERARCHY_FAIL = "GET_USERHIERARCHY_FAIL"

