export const GET_USERHIERARCHY = "GET_USERHIERARCHY";
export const GET_USERHIERARCHY_SUCCESS = "GET_USERHIERARCHY_SUCCESS";
export const GET_USERHIERARCHY_FAIL = "GET_USERHIERARCHY_FAIL";

export const ADD_USERHIERARCHY = "ADD_USERHIERARCHY";
export const ADD_USERHIERARCHY_SUCCESS = "ADD_USERHIERARCHY_SUCCESS";
export const ADD_USERHIERARCHY_FAIL = "ADD_USERHIERARCHY_FAIL";
