/* CUSTOMER USERS */
export const GET_OSDCONFIGURATION = "GET_OSDCONFIGURATION"
export const GET_OSDCONFIGURATION_SUCCESS = "GET_OSDCONFIGURATION_SUCCESS"
export const GET_OSDCONFIGURATION_FAIL = "GET_OSDCONFIGURATION_FAIL"

export const GET_OSDCONFIGURATION_ENABLE = "GET_OSDCONFIGURATION_ENABLE"
export const GET_OSDCONFIGURATION_ENABLE_SUCCESS = "GET_OSDCONFIGURATION_ENABLE_SUCCESS"
export const GET_OSDCONFIGURATION_ENABLE_FAIL = "GET_OSDCONFIGURATION_ENABLE_FAIL"

export const GET_OSDCONFIGURATION_FORCESDDISPLAY = "GET_OSDCONFIGURATION_FORCESDDISPLAY"
export const GET_OSDCONFIGURATION_FORCESDDISPLAY_SUCCESS = "GET_OSDCONFIGURATION_FORCESDDISPLAY_SUCCESS"
export const GET_OSDCONFIGURATION_FORCESDDISPLAY_FAIL = "GET_OSDCONFIGURATION_FORCESDDISPLAY_FAIL"

export const GET_OSDCONFIGURATION_DISPLAY = "GET_OSDCONFIGURATION_DISPLAY"
export const GET_OSDCONFIGURATION_DISPLAY_SUCCESS = "GET_OSDCONFIGURATION_DISPLAY_SUCCESS"
export const GET_OSDCONFIGURATION_DISPLAY_FAIL = "GET_OSDCONFIGURATION_DISPLAY_FAIL"

export const GET_OSDCONFIGURATION_FONTCOLOR = "GET_OSDCONFIGURATION_FONTCOLOR"
export const GET_OSDCONFIGURATION_FONTCOLOR_SUCCESS = "GET_OSDCONFIGURATION_FONTCOLOR_SUCCESS"
export const GET_OSDCONFIGURATION_FONTCOLOR_FAIL = "GET_OSDCONFIGURATION_FONTCOLOR_FAIL"

export const GET_OSDCONFIGURATION_BACKGROUNDAREA = "GET_OSDCONFIGURATION_BACKGROUNDAREA"
export const GET_OSDCONFIGURATION_BACKGROUNDAREA_SUCCESS = "GET_OSDCONFIGURATION_BACKGROUNDAREA_SUCCESS"
export const GET_OSDCONFIGURATION_BACKGROUNDAREA_FAIL = "GET_OSDCONFIGURATION_BACKGROUNDAREA_FAIL"

export const GET_OSDCONFIGURATION_FONTSIZE = "GET_OSDCONFIGURATION_FONTSIZE"
export const GET_OSDCONFIGURATION_FONTSIZE_SUCCESS = "GET_OSDCONFIGURATION_FONTSIZE_SUCCESS"
export const GET_OSDCONFIGURATION_FONTSIZE_FAIL = "GET_OSDCONFIGURATION_FONTSIZE_FAIL"

export const GET_OSDCONFIGURATION_BACKGROUNDCOLOR = "GET_OSDCONFIGURATION_BACKGROUNDCOLOR"
export const GET_OSDCONFIGURATION_BACKGROUNDCOLOR_SUCCESS = "GET_OSDCONFIGURATION_BACKGROUNDCOLOR_SUCCESS"
export const GET_OSDCONFIGURATION_BACKGROUNDCOLOR_FAIL = "GET_OSDCONFIGURATION_BACKGROUNDCOLOR_FAIL"

export const GET_OSDCONFIGURATION_STATUS = "GET_OSDCONFIGURATION_STATUS"
export const GET_OSDCONFIGURATION_STATUS_SUCCESS = "GET_OSDCONFIGURATION_STATUS_SUCCESS"
export const GET_OSDCONFIGURATION_STATUS_FAIL = "GET_OSDCONFIGURATION_STATUS_FAIL"





export const ADD_NEW_OSDCONFIGURATION =
    "ADD_NEW_OSDCONFIGURATION";
export const ADD_OSDCONFIGURATION_SUCCESS =
    "ADD_OSDCONFIGURATION_SUCCESS";
export const ADD_OSDCONFIGURATION_FAIL =
    "ADD_OSDCONFIGURATION_FAIL";
