/* CUSTOMER USERS */
export const GET_OSDCONFIGURATION = "GET_OSDCONFIGURATION"
export const GET_OSDCONFIGURATION_SUCCESS = "GET_OSDCONFIGURATION_SUCCESS"
export const GET_OSDCONFIGURATION_FAIL = "GET_OSDCONFIGURATION_FAIL"

export const ADD_NEW_OSDCONFIGURATION =
    "ADD_NEW_OSDCONFIGURATION";
export const ADD_OSDCONFIGURATION_SUCCESS =
    "ADD_OSDCONFIGURATION_SUCCESS";
export const ADD_OSDCONFIGURATION_FAIL =
    "ADD_OSDCONFIGURATION_FAIL";
