/* CUSTOMER USERS */
export const GET_OSDCONFIGURATION = "GET_OSDCONFIGURATION"
export const GET_OSDCONFIGURATION_SUCCESS = "GET_OSDCONFIGURATION_SUCCESS"
export const GET_OSDCONFIGURATION_FAIL = "GET_OSDCONFIGURATION_FAIL"

