export const GET_DISTRICT = "GET_DISTRICT";
export const GET_DISTRICT_SUCCESS = "GET_DISTRICT_SUCCESS";
export const GET_DISTRICT_FAIL = "GET_DISTRICT_FAIL";

export const ADD_DISTRICT = "ADD_DISTRICT";
export const ADD_DISTRICT_SUCCESS = "ADD_DISTRICT_SUCCESS";
export const ADD_DISTRICT_FAIL = "ADD_DISTRICT_FAIL";

export const GET_DISTRICT_STATUS = "GET_DISTRICT_STATUS";
export const GET_DISTRICT_STATUS_SUCCESS = "GET_DISTRICT_STATUS_SUCCESS";
export const GET_DISTRICT_STATUS_FAIL = "GET_DISTRICT_STATUS_FAIL";

export const GET_DISTRICT_STATELIST = "GET_DISTICT_STATELIST";
export const GET_DISTRICT_STATELIST_SUCCESS = "GET_DISTRICT_STATELIST_SUCCESS";
export const GET_DISTRICT_STATELIST_FAIL = "GET_DISTRICT_STATELIST_FAIL";
