export const GET_DISTRICT = "GET_DISTRICT";
export const GET_DISTRICT_SUCCESS = "GET_DISTRICT_SUCCESS";
export const GET_DISTRICT_FAIL = "GET_DISTRICT_FAIL";

export const ADD_DISTRICT = "ADD_DISTRICT";
export const ADD_DISTRICT_SUCCESS = "ADD_DISTRICT_SUCCESS";
export const ADD_DISTRICT_FAIL = "ADD_DISTRICT_FAIL";

export const GET_ADMINISTRATIVEDIVISION_STATUS =
  "GET_ADMINISTRATIVEDIVISION_STATUS";
export const GET_ADMINISTRATIVEDIVISION_STATUS_SUCCESS =
  "GET_ADMINISTRATIVEDIVISION_STATUS_SUCCESS";
export const GET_ADMINISTRATIVEDIVISION_STATUS_FAIL =
  "GET_ADMINISTRATIVEDIVISION_STATUS_FAIL";

export const GET_DISTRICT_STATELIST = "GET_DISTICT_STATELIST";
export const GET_DISTRICT_STATELIST_SUCCESS = "GET_DISTRICT_STATELIST_SUCCESS";
export const GET_DISTRICT_STATELIST_FAIL = "GET_DISTRICT_STATELIST_FAIL";

export const UPDATE_DISTRICT = "UPDATE_DISTRICT";
export const UPDATE_DISTRICT_SUCCESS = "UPDATE_DISTRICT_SUCCESS";
export const UPDATE_DISTRICT_FAIL = "UPDATE_DISTRICT_FAIL";

export const UPDATE_DISTRICT_CURRENT_PAGE = "UPDATE_DISTRICT_CURRENT_PAGE";