export const GET_INVENTORYSTATELIST = "GET_INVENTORYSTATELIST";
export const GET_INVENTORYSTATELIST_SUCCESS = "GET_INVENTORYSTATELIST_SUCCESS";
export const GET_INVENTORYSTATELIST_FAIL = "GET_INVENTORYSTATELIST_FAIL";

export const ADD_INVENTORYSTATELIST = "ADD_INVENTORYSTATELIST";
export const ADD_INVENTORYSTATELIST_SUCCESS = "ADD_INVENTORYSTATELIST_SUCCESS";
export const ADD_INVENTORYSTATELIST_FAIL = "ADD_INVENTORYSTATELIST_FAIL";
