/* CUSTOMER USERS */
export const GET_INVENTORYSTATELIST = "GET_INVENTORYSTATELIST";
export const GET_INVENTORYSTATELIST_SUCCESS = "GET_INVENTORYSTATELIST_SUCCESS";
export const GET_INVENTORYSTATELIST_FAIL = "GET_INVENTORYSTATELIST_FAIL";
