export const GET_TAX = "GET_TAX";
export const GET_TAX_SUCCESS = "GET_TAX_SUCCESS";
export const GET_TAX_FAIL = "GET_TAX_FAIL";

export const GET_TAX_STATUS = "GET_TAX_STATUS";
export const GET_TAX_STATUS_SUCCESS = "GET_TAX_STATUS_SUCCESS";
export const GET_TAX_STATUS_FAIL = "GET_TAX_STATUS_FAIL";

export const GET_TAX_VALUES = "GET_TAX_VALUES";
export const GET_TAX_VALUES_SUCCESS = "GET_TAX_VALUES_SUCCESS";
export const GET_TAX_VALUES_FAIL = "GET_TAX_VALUES_FAIL";

export const GET_TAX_APPLY = "GET_TAX_APPLY";
export const GET_TAX_APPLY_SUCCESS = "GET_TAX_APPLY_SUCCESS";
export const GET_TAX_APPLY_FAIL = "GET_TAX_APPLY_FAIL";

export const GET_TAX_TAXONTAX = "GET_TAX_TAXONTAX";
export const GET_TAX_TAXONTAX_SUCCESS = "GET_TAX_TAXONTAX_SUCCESS";
export const GET_TAX_TAXONTAX_FAIL = "GET_TAX_TAXONTAX_FAIL";

export const ADD_NEW_TAXLIST =
    "ADD_NEW_TAXLIST";
export const ADD_TAXLIST_SUCCESS =
    "ADD_TAXLIST_SUCCESS";
export const ADD_TAXLIST_FAIL =
    "ADD_TAXLIST_FAIL";
