export const GET_COMPLAINTSUBCATEGORY = "GET_COMPLAINTSUBCATEGORY";
export const GET_COMPLAINTSUBCATEGORY_SUCCESS =
  "GET_COMPLAINTSUBCATEGORY_SUCCESS";
export const GET_COMPLAINTSUBCATEGORY_FAIL = "GET_COMPLAINTSUBCATEGORY_FAIL";
