export const GET_COMPLAINTSUBCATEGORY = "GET_COMPLAINTSUBCATEGORY";
export const GET_COMPLAINTSUBCATEGORY_SUCCESS =
  "GET_COMPLAINTSUBCATEGORY_SUCCESS";
export const GET_COMPLAINTSUBCATEGORY_FAIL = "GET_COMPLAINTSUBCATEGORY_FAIL";

export const GET_COMPLAINTSUBCATEGORY_STATUS =
  "GET_COMPLAINTSUBCATEGORY_STATUS";
export const GET_COMPLAINTSUBCATEGORY_STATUS_SUCCESS =
  "GET_COMPLAINTSUBCATEGORY_STATUS_SUCCESS";
export const GET_COMPLAINTSUBCATEGORY_STATUS_FAIL =
  "GET_COMPLAINTSUBCATEGORY_STATUS_FAIL";

export const GET_COMPLAINTSUBCATEGORY_DESIGNATION =
  "GET_COMPLAINTSUBCATEGORY_DESIGNATION";
export const GET_COMPLAINTSUBCATEGORY_DESIGNATION_SUCCESS =
  "GET_COMPLAINTSUBCATEGORY_DESIGNATION_SUCCESS";
export const GET_COMPLAINTSUBCATEGORY_DESIGNATION_FAIL =
  "GET_COMPLAINTSUBCATEGORY_DESIGNATION_FAIL";

export const GET_COMPLAINTSUBCATEGORY_CATEGORY =
  "GET_COMPLAINTSUBCATEGORY_CATEGORY";
export const GET_COMPLAINTSUBCATEGORY_CATEGORY_SUCCESS =
  "GET_COMPLAINTSUBCATEGORY_CATEGORY_SUCCESS";
export const GET_COMPLAINTSUBCATEGORY_CATEGORY_FAIL =
  "GET_COMPLAINTSUBCATEGORY_CATEGORY_FAIL";

export const ADD_NEW_COMPLAINTSUBCATEGORY = "ADD_NEW_COMPLAINTSUBCATEGORY";
export const ADD_COMPLAINTSUBCATEGORY_SUCCESS =
  "ADD_COMPLAINTSUBCATEGORY_SUCCESS";
export const ADD_COMPLAINTSUBCATEGORY_FAIL = "ADD_COMPLAINTSUBCATEGORY_FAIL";

export const UPDATE_COMPLAINTSUBCATEGORY = "UPDATE_COMPLAINTSUBCATEGORY";
export const UPDATE_COMPLAINTSUBCATEGORY_SUCCESS =
  "UPDATE_COMPLAINTSUBCATEGORY_SUCCESS";
export const UPDATE_COMPLAINTSUBCATEGORY_FAIL =
  "UPDATE_COMPLAINTSUBCATEGORY_FAIL";
