export const GET_COMPLAINTSUBCATEGORY = "GET_COMPLAINTSUBCATEGORY";
export const GET_COMPLAINTSUBCATEGORY_SUCCESS =
  "GET_COMPLAINTSUBCATEGORY_SUCCESS";
export const GET_COMPLAINTSUBCATEGORY_FAIL = "GET_COMPLAINTSUBCATEGORY_FAIL";

export const ADD_NEW_COMPLAINTSUBCATEGORY =
  "ADD_NEW_COMPLAINTSUBCATEGORY";
export const ADD_COMPLAINTSUBCATEGORY_SUCCESS =
  "ADD_COMPLAINTSUBCATEGORY_SUCCESS";
export const ADD_COMPLAINTSUBCATEGORY_FAIL =
  "ADD_COMPLAINTSUBCATEGORY_FAIL";