export const GET_BANK = "GET_BANK";
export const GET_BANK_SUCCESS = "GET_BANK_SUCCESS";
export const GET_BANK_FAIL = "GET_BANK_FAIL";

export const GET_BANK_STATUS = "GET_BANK_STATUS";
export const GET_BANK_STATUS_SUCCESS = "GET_BANK_STATUS_SUCCESS";
export const GET_BANK_STATUS_FAIL = "GET_BANK_STATUS_FAIL";

export const ADD_NEW_BANK =
    "ADD_NEW_BANK";
export const ADD_BANK_SUCCESS =
    "ADD_BANK_SUCCESS";
export const ADD_BANK_FAIL =
    "ADD_BANK_FAIL";
