export const GET_INVENTORYFAULTY_SMARTCARD = "GET_INVENTORYFAULTY_SMARTCARD";
export const GET_INVENTORYFAULTY_SMARTCARD_SUCCESS =
  "GET_INVENTORYFAULTY_SMARTCARD_SUCCESS";
export const GET_INVENTORYFAULTY_SMARTCARD_FAIL =
  "GET_INVENTORYFAULTY_SMARTCARD_FAIL";

export const GET_INVENTORYFAULTY_STB = "GET_INVENTORYFAULTY_STB";
export const GET_INVENTORYFAULTY_STB_SUCCESS =
  "GET_INVENTORYFAULTY_STB_SUCCESS";
export const GET_INVENTORYFAULTY_STB_FAIL = "GET_INVENTORYFAULTY_STB_FAIL";

export const GET_INVENTORYFAULTY_PAIRING = "GET_INVENTORYFAULTY_PAIRING";
export const GET_INVENTORYFAULTY_PAIRING_SUCCESS =
  "GET_INVENTORYFAULTY_PAIRING_SUCCESS";
export const GET_INVENTORYFAULTY_PAIRING_FAIL =
  "GET_INVENTORYFAULTY_PAIRING_FAIL";

export const UPDATE_STOCKPAIRING_CURRENT_PAGE =
  "UPDATE_STOCKPAIRING_CURRENT_PAGE";
export const UPDATE_FAULTYPAIRING_CURRENT_PAGE =
  "UPDATE_FAULTYPAIRING_CURRENT_PAGE";
