export const GET_INVENTORYFAULTY_SMARTCARD = "GET_INVENTORYFAULTY_SMARTCARD";
export const GET_INVENTORYFAULTY_SMARTCARD_SUCCESS =
  "GET_INVENTORYFAULTY_SMARTCARD_SUCCESS";
export const GET_INVENTORYFAULTY_SMARTCARD_FAIL =
  "GET_INVENTORYFAULTY_SMARTCARD_FAIL";

export const GET_INVENTORYFAULTY_STB = "GET_INVENTORYFAULTY_STB";
export const GET_INVENTORYFAULTY_STB_SUCCESS =
  "GET_INVENTORYFAULTY_STB_SUCCESS";
export const GET_INVENTORYFAULTY_STB_FAIL = "GET_INVENTORYFAULTY_STB_FAIL";

export const GET_INVENTORYFAULTY_PAIRING = "GET_INVENTORYFAULTY_PAIRING";
export const GET_INVENTORYFAULTY_PAIRING_SUCCESS =
  "GET_INVENTORYFAULTY_PAIRING_SUCCESS";
export const GET_INVENTORYFAULTY_PAIRING_FAIL =
  "GET_INVENTORYFAULTY_PAIRING_FAIL";

export const UPDATE_FAULTYPAIRING_CURRENT_PAGE =
  "UPDATE_FAULTYPAIRING_CURRENT_PAGE";

export const UPDATE_FAULTYSMARTCARD_SENDSC = "UPDATE_FAULTYSMARTCARD_SENDSC";
export const UPDATE_FAULTYSMARTCARD_SENDSC_SUCCESS =
  "UPDATE_FAULTYSMARTCARD_SENDSC_SUCCESS";
export const UPDATE_FAULTYSMARTCARD_SENDSC_FAIL =
  "UPDATE_FAULTYSMARTCARD_SENDSC_FAIL";

export const UPDATE_FAULTYSMARTCARD_BLACKLIST =
  "UPDATE_FAULTYSMARTCARD_BLACKLIST";
export const UPDATE_FAULTYSMARTCARD_BLACKLIST_SUCCESS =
  "UPDATE_FAULTYSMARTCARD_BLACKLIST_SUCCESS";
export const UPDATE_FAULTYSMARTCARD_BLACKLIST_FAIL =
  "UPDATE_FAULTYSMARTCARD_BLACKLIST_FAIL";

export const UPDATE_FAULTYSTB_SENDSTB = "UPDATE_FAULTYSTB_SENDSTB";
export const UPDATE_FAULTYSTB_SENDSTB_SUCCESS =
  "UPDATE_FAULTYSTB_SENDSTB_SUCCESS";
export const UPDATE_FAULTYSTB_SENDSTB_FAIL = "UPDATE_FAULTYSTB_SENDSTB_FAIL";

export const UPDATE_FAULTYSTB_BLACKLIST = "UPDATE_FAULTYSTB_BLACKLIST";
export const UPDATE_FAULTYSTB_BLACKLIST_SUCCESS =
  "UPDATE_FAULTYSTB_BLACKLIST_SUCCESS";
export const UPDATE_FAULTYSTB_BLACKLIST_FAIL =
  "UPDATE_FAULTYSTB_BLACKLIST_FAIL";

export const UPDATE_FAULTYPAIRING_SENDPAIR = "UPDATE_FAULTYPAIRING_SENDPAIR";
export const UPDATE_FAULTYPAIRING_SENDPAIR_SUCCESS =
  "UPDATE_FAULTYPAIR_SENDPAIRING_SUCCESS";
export const UPDATE_FAULTYPAIRING_SENDPAIR_FAIL =
  "UPDATE_FAULTYPAIRING_SENDPAIR_FAIL";

export const UPDATE_FAULTYPAIRING_BLACKLIST = "UPDATE_FAULTYPAIRING_BLACKLIST";
export const UPDATE_FAULTYPAIRING_BLACKLIST_SUCCESS =
  "UPDATE_FAULTYPAIRING_BLACKLIST_SUCCESS";
export const UPDATE_FAULTYPAIRING_BLACKLIST_FAIL =
  "UPDATE_FAULTYPAIRING_BLACKLIST_FAIL";
