/* CUSTOMER USERS */
export const GET_OSDTEMPLATE = "GET_OSDTEMPLATE"
export const GET_OSDTEMPLATE_SUCCESS = "GET_OSDTEMPLATE_SUCCESS"
export const GET_OSDTEMPLATE_FAIL = "GET_OSDTEMPLATE_FAIL"

export const UPDATE_OSDTEMPLATE = "UPDATE_OSDTEMPLATE";
export const UPDATE_OSDTEMPLATE_SUCCESS = "UPDATE_OSDTEMPLATE_SUCCESS";
export const UPDATE_OSDTEMPLATE_FAIL = "UPDATE_OSDTEMPLATE_FAIL";

export const GET_OSDTEMPLATE_STATUS = "GET_OSDTEMPLATE_STATUS"
export const GET_OSDTEMPLATE_STATUS_SUCCESS = "GET_OSDTEMPLATE_STATUS_SUCCESS"
export const GET_OSDTEMPLATE_STATUS_FAIL = "GET_OSDTEMPLATE_STATUS_FAIL"

export const GET_OSDTEMPLATE_OSD = "GET_OSDTEMPLATE_OSD"
export const GET_OSDTEMPLATE_OSD_SUCCESS = "GET_OSDTEMPLATE_OSD_SUCCESS"
export const GET_OSDTEMPLATE_OSD_FAIL = "GET_OSDTEMPLATE_OSD_FAIL"

export const GET_OSDTEMPLATE_TEMPLATEFOR = "GET_OSDTEMPLATE_TEMPLATEFOR"
export const GET_OSDTEMPLATE_TEMPLATEFOR_SUCCESS = "GET_OSDTEMPLATE_TEMPLATEFOR_SUCCESS"
export const GET_OSDTEMPLATE_TEMPLATEFOR_FAIL = "GET_OSDTEMPLATE_TEMPLATEFOR_FAIL"

export const ADD_NEW_OSDTEMPLATE =
    "ADD_NEW_OSDTEMPLATE";
export const ADD_OSDTEMPLATE_SUCCESS =
    "ADD_OSDTEMPLATE_SUCCESS";
export const ADD_OSDTEMPLATE_FAIL =
    "ADD_OSDTEMPLATE_FAIL";

export const UPDATE_OSDTEMPLATE_CURRENT_PAGE = "UPDATE_OSDTEMPLATE_CURRENT_PAGE";
