/* CUSTOMER USERS */
export const GET_OSDTEMPLATE = "GET_OSDTEMPLATE"
export const GET_OSDTEMPLATE_SUCCESS = "GET_OSDTEMPLATE_SUCCESS"
export const GET_OSDTEMPLATE_FAIL = "GET_OSDTEMPLATE_FAIL"

export const ADD_NEW_OSDTEMPLATE =
    "ADD_NEW_OSDTEMPLATE";
export const ADD_OSDTEMPLATE_SUCCESS =
    "ADD_OSDTEMPLATE_SUCCESS";
export const ADD_OSDTEMPLATE_FAIL =
    "ADD_OSDTEMPLATE_FAIL";
