export const GET_CONFIGURATIONUPLOADLOGS = "GET_CONFIGURATIONUPLOADLOGS";
export const GET_CONFIGURATIONUPLOADLOGS_SUCCESS =
  "GET_CONFIGURATIONUPLOADLOGS_SUCCESS";
export const GET_CONFIGURATIONUPLOADLOGS_FAIL =
  "GET_CONFIGURATIONUPLOADLOGS_FAIL";

export const UPDATE_CONFIGURATIONUPLOADLOGS_CURRENT_PAGE = "UPDATE_CONFIGURATIONUPLOADLOGS_CURRENT_PAGE";