export const GET_CONFIGURATIONUPLOADLOGS = "GET_CONFIGURATIONUPLOADLOGS";
export const GET_CONFIGURATIONUPLOADLOGS_SUCCESS =
  "GET_CONFIGURATIONUPLOADLOGS_SUCCESS";
export const GET_CONFIGURATIONUPLOADLOGS_FAIL =
  "GET_CONFIGURATIONUPLOADLOGS_FAIL";
