/* CUSTOMER USERS */
export const GET_NOTIFICATIONTEMPLATE = "GET_NOTIFICATIONTEMPLATE";
export const GET_NOTIFICATIONTEMPLATE_SUCCESS =
  "GET_NOTIFICATIONTEMPLATE_SUCCESS";
export const GET_NOTIFICATIONTEMPLATE_FAIL = "GET_NOTIFICATIONTEMPLATE_FAIL";

export const ADD_NEW_NOTIFICATIONTEMPLATE = "ADD_NEW_NOTIFICATIONTEMPLATE";
export const ADD_NOTIFICATIONTEMPLATE_SUCCESS =
  "ADD_NOTIFICATIONTEMPLATE_SUCCESS";
export const ADD_NOTIFICATIONTEMPLATE_FAIL = "ADD_NOTIFICATIONTEMPLATE_FAIL";
