/* CUSTOMER USERS */
export const GET_NOTIFICATIONTEMPLATE = "GET_NOTIFICATIONTEMPLATE"
export const GET_NOTIFICATIONTEMPLATE_SUCCESS = "GET_NOTIFICATIONTEMPLATE_SUCCESS"
export const GET_NOTIFICATIONTEMPLATE_FAIL = "GET_NOTIFICATIONTEMPLATE_FAIL"

