/* CUSTOMER USERS */
export const GET_NOTIFICATIONTEMPLATE = "GET_NOTIFICATIONTEMPLATE";
export const GET_NOTIFICATIONTEMPLATE_SUCCESS =
  "GET_NOTIFICATIONTEMPLATE_SUCCESS";
export const GET_NOTIFICATIONTEMPLATE_FAIL = "GET_NOTIFICATIONTEMPLATE_FAIL";

export const GET_NOTIFICATIONTEMPLATE_TYPE = "GET_NOTIFICATIONTEMPLATE_TYPE";
export const GET_NOTIFICATIONTEMPLATE_TYPE_SUCCESS =
  "GET_NOTIFICATIONTEMPLATE_TYPE_SUCCESS";
export const GET_NOTIFICATIONTEMPLATE_TYPE_FAIL =
  "GET_NOTIFICATIONTEMPLATE_TYPE_FAIL";

export const GET_NOTIFICATIONTEMPLATE_STATUS =
  "GET_NOTIFICATIONTEMPLATE_STATUS";
export const GET_NOTIFICATIONTEMPLATE_STATUS_SUCCESS =
  "GET_NOTIFICATIONTEMPLATE_STATUS_SUCCESS";
export const GET_NOTIFICATIONTEMPLATE_STATUS_FAIL =
  "GET_NOTIFICATIONTEMPLATE_STATUS_FAIL";

export const ADD_NEW_NOTIFICATIONTEMPLATE = "ADD_NEW_NOTIFICATIONTEMPLATE";
export const ADD_NOTIFICATIONTEMPLATE_SUCCESS =
  "ADD_NOTIFICATIONTEMPLATE_SUCCESS";
export const ADD_NOTIFICATIONTEMPLATE_FAIL = "ADD_NOTIFICATIONTEMPLATE_FAIL";

export const UPDATE_NOTIFICATIONTEMPLATE = "UPDATE_NOTIFICATIONTEMPLATE";
export const UPDATE_NOTIFICATIONTEMPLATE_SUCCESS =
  "UPDATE_NOTIFICATIONTEMPLATE_SUCCESS";
export const UPDATE_NOTIFICATIONTEMPLATE_FAIL =
  "UPDATE_NOTIFICATIONTEMPLATE_FAIL";

export const GET_NOTIFICATIONTEMPLATE_ADDUSER =
  "GET_NOTIFICATIONTEMPLATE_ADDUSER";
export const GET_NOTIFICATIONTEMPLATE_ADDUSER_SUCCESS =
  "GET_NOTIFICATIONTEMPLATE_ADDUSER_SUCCESS";
export const GET_NOTIFICATIONTEMPLATE_ADDUSER_FAIL =
  "GET_NOTIFICATIONTEMPLATE_ADDUSER_FAIL";
