export const GET_CITY = "GET_CITY";
export const GET_CITY_SUCCESS = "GET_CITY_SUCCESS";
export const GET_CITY_FAIL = "GET_CITY_FAIL";

export const ADD_CITY = "ADD_CITY";
export const ADD_CITY_SUCCESS = "ADD_CITY_SUCCESS";
export const ADD_CITY_FAIL = "ADD_CITY_FAIL";

export const GET_DISTRICT_BYSTATEID = "GET_DISTRICT_BYSTATEID";
export const GET_DISTRICT_BYSTATEID_SUCCESS = "GET_DISTRICT_BYSTATEID_SUCCESS";
export const GET_DISTRICT_BYSTATEID_FAIL = "GET_DISTRICT_BYSTATEID_FAIL";
