export const GET_PROMOVOUCHER = "GET_PROMOVOUCHER";
export const GET_PROMOVOUCHER_SUCCESS = "GET_PROMOVOUCHER_SUCCESS";
export const GET_PROMOVOUCHER_FAIL = "GET_PROMOVOUCHER_FAIL";

export const GET_PROMOVOUCHER_LCO = "GET_PROMOVOUCHER_LCO";
export const GET_PROMOVOUCHER_LCO_SUCCESS = "GET_PROMOVOUCHER_LCO_SUCCESS";
export const GET_PROMOVOUCHER_LCO_FAIL = "GET_PROMOVOUCHER_LCO_FAIL";

export const GET_PROMOVOUCHER_APPLY = "GET_PROMOVOUCHER_APPLY";
export const GET_PROMOVOUCHER_APPLY_SUCCESS = "GET_PROMOVOUCHER_APPLY_SUCCESS";
export const GET_PROMOVOUCHER_APPLY_FAIL = "GET_PROMOVOUCHER_APPLY_FAIL";

export const GET_PROMOVOUCHER_BOUQUET = "GET_PROMOVOUCHER_BOUQUET";
export const GET_PROMOVOUCHER_BOUQUET_SUCCESS = "GET_PROMOVOUCHER_BOUQUET_SUCCESS";
export const GET_PROMOVOUCHER_BOUQUET_FAIL = "GET_PROMOVOUCHER_BOUQUET_FAIL";

export const GET_PROMOVOUCHER_RECHARGE = "GET_PROMOVOUCHER_RECHARGE";
export const GET_PROMOVOUCHER_RECHARGE_SUCCESS = "GET_PROMOVOUCHER_RECHARGE_SUCCESS";
export const GET_PROMOVOUCHER_RECHARGE_FAIL = "GET_PROMOVOUCHER_RECHARGE_FAIL";

export const ADD_NEW_PROMOVOUCHER =
    "ADD_NEW_PROMOVOUCHER";
export const ADD_PROMOVOUCHER_SUCCESS =
    "ADD_PROMOVOUCHER_SUCCESS";
export const ADD_PROMOVOUCHER_FAIL =
    "ADD_PROMOVOUCHER_FAIL";

export const ADD_PROMOVOUCHER_SCRAP =
    "ADD_PROMOVOUCHER_SCRAP";
export const ADD_PROMOVOUCHER_SCRAP_SUCCESS =
    "ADD_PROMOVOUCHER_SCRAP_SUCCESS";
export const ADD_PROMOVOUCHER_SCRAP_FAIL =
    "ADD_PROMOVOUCHER_SCRAP_FAIL";

export const UPDATE_PROMOVOUCHER_CURRENT_PAGE = "UPDATE_USERS_CURRENT_PAGE";