export const GET_PROMOVOUCHER = "GET_PROMOVOUCHER";
export const GET_PROMOVOUCHER_SUCCESS = "GET_PROMOVOUCHER_SUCCESS";
export const GET_PROMOVOUCHER_FAIL = "GET_PROMOVOUCHER_FAIL";

export const ADD_NEW_PROMOVOUCHER =
    "ADD_NEW_PROMOVOUCHER";
export const ADD_PROMOVOUCHER_SUCCESS =
    "ADD_PROMOVOUCHER_SUCCESS";
export const ADD_PROMOVOUCHER_FAIL =
    "ADD_PROMOVOUCHER_FAIL";
