export const GET_LCO = "GET_LCO";
export const GET_LCO_SUCCESS = "GET_LCO_SUCCESS";
export const GET_LCO_FAIL = "GET_LCO_FAIL";

export const GET_LCO_BILLEDBY = "GET_LCO_BILLEDBY";
export const GET_LCO_BILLEDBY_SUCCESS = "GET_LCO_BILLEDBY_SUCCESS";
export const GET_LCO_BILLEDBY_FAIL = "GET_LCO_BILLEDBY_FAIL";

export const GET_LCO_STATUS = "GET_LCO_STATUS";
export const GET_LCO_STATUS_SUCCESS = "GET_LCO_STATUS_SUCCESS";
export const GET_LCO_STATUS_FAIL = "GET_LCO_STATUS_FAIL ";

export const GET_LCO_PHASE = "GET_LCO_PHASE";
export const GET_LCO_PHASE_SUCCESS = "LCO_PHASE_SUCCESS";
export const GET_LCO_PHASE_FAIL = "GET_LCO_PHASE_FAIL";

export const GET_LCO_STATES = "GET_LCO_STATES";
export const GET_LCO_STATES_SUCCESS = "GET_LCO_STATES_SUCCESS";
export const GET_LCO_STATES_FAIL = "GET_LCO_STATES_FAIL";

export const GET_LCO_CUSTOMERPORTAL = "GET_LCO_CUSTOMERPORTAL";
export const GET_LCO_CUSTOMERPORTAL_SUCCESS = "GET_LCO_CUSTOMERPORTAL_SUCCESS ";
export const GET_LCO_CUSTOMERPORTAL_FAIL = "GET_LCO_CUSTOMERPORTAL_FAIL";

export const GET_LCO_PARENTDISTRIBUTOR = "GET_LCO_PARENTDISTRIBUTOR";
export const GET_LCO_PARENTDISTRIBUTOR_SUCCESS =
  "GET_LCO_PARENTDISTRIBUTOR_SUCCESS";
export const GET_LCO_PARENTDISTRIBUTOR_FAIL = "GET_LCO_PARENTDISTRIBUTOR_FAIL";

export const GET_SINGLE_LCO = "GET_SINGLE_LCO";
export const GET_SINGLE_LCO_SUCCESS = "GET_SINGLE_LCO_SUCCESS";
export const GET_SINGLE_LCO_FAIL = "GET_SINGLE_LCO_FAIL";

export const ADD_NEW_LCO = "ADD_NEW_LCO";
export const ADD_LCO_SUCCESS = "ADD_LCO_SUCCESS";
export const ADD_LCO_FAIL = "ADD_LCO_FAIL";

export const UPDATE_LCO = "UPDATE_LCO";
export const UPDATE_LCO_SUCCESS = "UPDATE_LCO_SUCCESS";
export const UPDATE_LCO_FAIL = "UPDATE_LCO_FAIL";

export const UPDATE_LCO_CURRENT_PAGE = "UPDATE_LCO_CURRENT_PAGE";

export const GET_LCO_PAYMENTMODE = "GET_LCO_PAYMENTMODE";
export const GET_LCO_PAYMENTMODE_SUCCESS = "GET_LCO_PAYMENTMODE_SUCCESS";
export const GET_LCO_PAYMENTMODE_FAIL = "GET_LCO_PAYMENTMODE_FAIL";

export const GET_LCO_ADDCREDIT = "GET_LCO_ADDCREDIT";
export const GET_LCO_ADDCREDIT_SUCCESS = "GET_LCO_ADDCREDIT_SUCCESS";
export const GET_LCO_ADDCREDIT_FAIL = "GET_LCO_ADDCREDIT_FAIL";
