export const GET_SCHEDULEDNOTIFICATION = "GET_SCHEDULEDNOTIFICATION";
export const GET_SCHEDULEDNOTIFICATION_SUCCESS =
  "GET_SCHEDULEDNOTIFICATION_SUCCESS";
export const GET_SCHEDULEDNOTIFICATION_FAIL = "GET_SCHEDULEDNOTIFICATION_FAIL";
