export const GET_DISTRIBUTORS = "GET_DISTRIBUTORS";
export const GET_DISTRIBUTORS_SUCCESS = "GET_DISTRIBUTORS_SUCCESS";
export const GET_DISTRIBUTORS_FAIL = "GET_DISTRIBUTORS_FAIL";

export const ADD_NEW_DISTRIBUTOR = "ADD_NEW_DISTRIBUTOR";
export const ADD_DISTRIBUTORS_SUCCESS = "ADD_DISTRIBUTORS_SUCCESS";
export const ADD_DISTRIBUTORS_FAIL = "ADD_DISTRIBUTORS_FAIL";

export const UPDATE_DISTRIBUTOR = "UPDATE_DISTRIBUTOR";
export const UPDATE_DISTRIBUTORS_SUCCESS = "UPDATE_DISTRIBUTORS_SUCCESS";
export const UPDATE_DISTRIBUTORS_FAIL = "UPDATE_DISTRIBUTORS_FAIL";
