export const GET_WAREHOUSELIST = "GET_WAREHOUSELIST";
export const GET_WAREHOUSELIST_SUCCESS = "GET_WAREHOUSELIST_SUCCESS";
export const GET_WAREHOUSELIST_FAIL = "GET_WAREHOUSELIST_FAIL";

export const UPDATE_WAREHOUSELIST = "UPDATE_WAREHOUSELIST";
export const UPDATE_WAREHOUSELIST_SUCCESS = "UPDATE_WAREHOUSELIST_SUCCESS";
export const UPDATE_WAREHOUSELIST_FAIL = "UPDATE_WAREHOUSELIST_FAIL";

export const GET_WAREHOUSELIST_STATUS = "GET_WAREHOUSELIST_STATUS";
export const GET_WAREHOUSELIST_STATUS_SUCCESS = "GET_WAREHOUSELIST_STATUS_SUCCESS";
export const GET_WAREHOUSELIST_STATUS_FAIL = "GET_WAREHOUSELIST_STATUS_FAIL";

export const GET_WAREHOUSELIST_OPERATOR = "GET_WAREHOUSELIST_OPERATOR";
export const GET_WAREHOUSELIST_OPERATOR_SUCCESS = "GET_WAREHOUSELIST_OPERATOR_SUCCESS";
export const GET_WAREHOUSELIST_OPERATOR_FAIL = "GET_WAREHOUSELIST_OPERATOR_FAIL";

export const ADD_WAREHOUSELIST = "ADD_WAREHOUSELIST";
export const ADD_WAREHOUSELIST_SUCCESS = "ADD_WAREHOUSELIST_SUCCESS";
export const ADD_WAREHOUSELIST_FAIL = "ADD_WAREHOUSELIST_FAIL";

export const UPDATE_WAREHOUSELIST_CURRENT_PAGE = "UPDATE_WAREHOUSELIST_CURRENT_PAGE";