/* CUSTOMER USERS */
export const GET_WAREHOUSELIST = "GET_WAREHOUSELIST";
export const GET_WAREHOUSELIST_SUCCESS = "GET_WAREHOUSELIST_SUCCESS";
export const GET_WAREHOUSELIST_FAIL = "GET_WAREHOUSELIST_FAIL";
