export const GET_WAREHOUSELIST = "GET_WAREHOUSELIST";
export const GET_WAREHOUSELIST_SUCCESS = "GET_WAREHOUSELIST_SUCCESS";
export const GET_WAREHOUSELIST_FAIL = "GET_WAREHOUSELIST_FAIL";

export const ADD_WAREHOUSELIST = "ADD_WAREHOUSELIST";
export const ADD_WAREHOUSELIST_SUCCESS = "ADD_WAREHOUSELIST_SUCCESS";
export const ADD_WAREHOUSELIST_FAIL = "ADD_WAREHOUSELIST_FAIL";
