/* CUSTOMER USERS */
export const GET_ADMINDETAILS = "GET_ADMINDETAILS";
export const GET_ADMINDETAILS_SUCCESS = "GET_ADMINDETAILS_SUCCESS";
export const GET_ADMINDETAILSGET_CHANNELLIST_FAIL = "GET_ADMINDETAILS_FAIL";
